from lang_constraints import num_violations_validity_only
from fandango import Fandango
from fandango.language.parse import parse

# This file contains code generated by Copilot.

fan_file = "./lang_validity_and_size.fan"

def run_once(all_programs, fine_print = False, print_successful_programs = True):
    # Open the file
    with open(fan_file, "r") as f:
        fan_contents = f.read()

    # Initialize Fandango with the grammar file
    langfuzzer = Fandango(fan_contents)
    print("Fandango specification loaded.")

    # Generate a random program
    # Time this process
    import time
    start_time = time.time()
    programs = langfuzzer.fuzz(desired_solutions=100, population_size=30, max_nodes=1000)
    # programs = langfuzzer.fuzz(desired_solutions=100, population_size=10, max_nodes=10000)
    # programs = langfuzzer.fuzz(desired_solutions=100, population_size=1000, max_nodes=10000)
    end_time = time.time()

    total_programs_generated = 0
    total_programs_fitness_1 = 0
    total_programs_accepted_by_gcc = 0

    # Print solutions
    compile_time_start = time.time()
    for i, program in enumerate(programs):
        total_programs_generated += 1
        if fine_print:
            print("="*40)
            print(f"Program {i+1}:\n{program}\n")
        # Check constraints
        tree = program
        if num_violations_validity_only(tree, should_print = False) > 0:
            if fine_print:
                print("Violations found in this program.")
        else:
            if fine_print:
                print("No Violations found in this program.")
            total_programs_fitness_1 += 1
            # Pipe to compiler
            import subprocess
            # Set up includes
            includes = "#include <stdio.h>\n#include <stdbool.h>\n"
            prog_str = includes + str(program)
            # Add main if not present
            if "fn main()" not in prog_str:
                prog_str += "\nint main() { return 0; }\n"
            # Compile using gcc
            compile_process = subprocess.run(["gcc", "-x", "c", "-o", "/dev/null", "-"], input=prog_str.encode(), capture_output=True)
            compile_result = compile_process.returncode
            if compile_result == 0:
                all_programs.append(program)
                if fine_print:
                    print(f"Program {i+1} compiled successfully.")
                if print_successful_programs:
                    print(f"Successful Program {i+1}:\n{program}\n")
                total_programs_accepted_by_gcc += 1
            else:
                if fine_print:
                    print(f"Program {i+1} failed to compile.")
                    print(compile_process.stderr.decode())
                    print(program)
    compile_time_end = time.time()
    # Time summary.
    print(f"Generated {len(programs)} programs in {end_time - start_time:.2f} seconds.")
    # Compile time.
    print(f"Total compile time: {compile_time_end - compile_time_start:.2f} seconds.")

    # Print results
    return (total_programs_generated, total_programs_fitness_1, total_programs_accepted_by_gcc, end_time - start_time, compile_time_end - compile_time_start)

def run_repl():
    # Run run_once repeatedly for 1 minute
    import time
    end_time = time.time() + 60  # Run for 60 seconds
    total_generated = 0
    total_fitness_1 = 0
    total_accepted_by_gcc = 0
    total_gen_time = 0
    total_compile_time = 0
    runs = 0

    # Collect all programs
    all_programs = []

    while time.time() < end_time:
        print(f"Run {runs+1}:")
        gen, fit1, gcc, gen_time, compile_time = run_once(all_programs, fine_print=False, print_successful_programs=False)
        total_generated += gen
        total_fitness_1 += fit1
        total_accepted_by_gcc += gcc
        total_gen_time += gen_time
        total_compile_time += compile_time
        runs += 1
    print("="*40)
    print(f"Ran {runs} times in 60 seconds.")

    # Compute the coverage
    with open(fan_file, "r") as file:
        grammar, constraints = parse(file, use_stdlib=False)
        assert grammar is not None

    coverage = grammar.compute_grammar_coverage(all_programs, 5)

    # Print coverage
    print("Coverage:", coverage)

    coverage_percentage = coverage[0] * 100
    # round to 2 decimal places
    coverage_percentage = round(coverage_percentage, 2)

    return (coverage_percentage, total_generated, total_fitness_1, total_accepted_by_gcc, total_gen_time, total_compile_time)

if __name__ == "__main__":

    total_runs = 5

    total_coverage_percentage = 0
    total_generated = 0
    total_fitness_1 = 0
    total_accepted_by_gcc = 0
    total_gen_time = 0
    total_compile_time = 0

    for run in range(total_runs):
        print(f"=== Run {run+1} of {total_runs} ===")
        run_coverage_percent, run_generated, run_fitness_1, run_accepted_by_gcc, run_gen_time, run_compile_time = run_repl()
        total_coverage_percentage += run_coverage_percent
        total_generated += run_generated
        total_fitness_1 += run_fitness_1
        total_accepted_by_gcc += run_accepted_by_gcc
        total_gen_time += run_gen_time
        total_compile_time += run_compile_time
    
    avg_coverage_percentage = round(total_coverage_percentage / total_runs, 2)
    avg_total_generated = round(total_generated / total_runs)
    avg_total_fitness_1 = round(total_fitness_1 / total_runs)
    avg_total_accepted_by_gcc = round(total_accepted_by_gcc / total_runs)
    avg_total_gen_time = total_gen_time / total_runs
    avg_total_compile_time = total_compile_time / total_runs

    print("Averages over all runs:")

    # Print LaTeX commands
    print(f"\\newcommand{{\\validAndSizedConstrainedKPathCoverageAvgPy}}{{{avg_coverage_percentage}\\%\\xspace}}")
    print(f"\\newcommand{{\\validAndSizedConstrainedTotalAvgPy}}{{{avg_total_generated}\\xspace}}")
    print(f"\\newcommand{{\\validAndSizedConstrainedFitOneAvgPy}}{{{avg_total_fitness_1}\\xspace}}")
    print(f"\\newcommand{{\\validAndSizedConstrainedCompileAvgPy}}{{{avg_total_accepted_by_gcc}\\xspace}}")
    print(f"\\newcommand{{\\validAndSizedConstrainedGenTimeAvgPy}}{{{avg_total_gen_time:.2f}s\\xspace}}")
    print(f"\\newcommand{{\\validAndSizedConstrainedCompileTimeAvgPy}}{{{avg_total_compile_time:.2f}s\\xspace}}")
    print(f"\\newcommand{{\\validAndSizedConstrainedTotalTimeAvgPy}}{{{(avg_total_gen_time + avg_total_compile_time):.2f}s\\xspace}}")

    # Also write to a file
    with open("c_lang_validity_and_size_results_python.txt", "w") as result_file:
        result_file.write(f"\\newcommand{{\\validAndSizedConstrainedKPathCoverageAvgPy}}{{{avg_coverage_percentage}\\%\\xspace}}\n")
        result_file.write(f"\\newcommand{{\\validAndSizedConstrainedTotalAvgPy}}{{{avg_total_generated}\\xspace}}\n")
        result_file.write(f"\\newcommand{{\\validAndSizedConstrainedFitOneAvgPy}}{{{avg_total_fitness_1}\\xspace}}\n")
        result_file.write(f"\\newcommand{{\\validAndSizedConstrainedCompileAvgPy}}{{{avg_total_accepted_by_gcc}\\xspace}}\n")
        result_file.write(f"\\newcommand{{\\validAndSizedConstrainedGenTimeAvgPy}}{{{avg_total_gen_time:.2f}s\\xspace}}\n")
        result_file.write(f"\\newcommand{{\\validAndSizedConstrainedCompileTimeAvgPy}}{{{avg_total_compile_time:.2f}s\\xspace}}\n")
        result_file.write(f"\\newcommand{{\\validAndSizedConstrainedTotalTimeAvgPy}}{{{(avg_total_gen_time + avg_total_compile_time):.2f}s\\xspace}}\n")