# for debugging:
import traceback

# This file contains code generated by Copilot.

C_RESERVED_WORDS = {
    "auto", "else", "long", "switch",
    "break", "enum", "register", "typedef",
    "case", "extern", "return", "union",
    "char", "float", "short", "unsigned",
    "const", "for", "signed", "void",
    "continue", "goto", "sizeof", "volatile",
    "default", "if", "static", "while",
    "do", "int", "struct", "_Packed",
    "double"
}

# Base derivation tree visitor class.
# Define your own visitors by inheriting from this class, and
# overriding the visit_<node_name> methods.
# You are responsible for recursively visiting children nodes.
class DerivationTreeVisitor:
    def visit(self, node):
        method_name = f'visit_{get_node_name(node)}'
        visitor = getattr(self, method_name, self.generic_visit)
        return visitor(node)

    def generic_visit(self, node):
        for child in getattr(node, 'children', []):
            self.visit(child)

# Classes and helpers
#
def get_node_name(dt_node):
    return dt_node.symbol.symbol.strip('<>')

class VarSymbolTable:
    def __init__(self):
        self.symbols = dict()

    def define(self, var_name, scope_trace, type):
        self.symbols[(var_name, scope_trace)] = type

    def get_type(self, var_name, scope_trace):
        return self.symbols.get((var_name, scope_trace), None)

class FuncSymbolTable:
    def __init__(self):
        self.symbols = dict()

    def define(self, func_name, scope_trace, param_types, return_type):
        self.symbols[(func_name, scope_trace)] = (param_types, return_type)

    def get_signature(self, func_name, scope_trace):
        return self.symbols.get((func_name, scope_trace), None)

# Get the function name and type for the innermost function in the scope trace.
# It's possible that no function is in a scope trace (e.g., we are in an if),
# so go through again with a smaller scope trace.
def get_current_function(func_symbol_table, scope_trace):
    for i in range(len(scope_trace), -1, -1):
        sub_trace = scope_trace[:i]
        for (func_name, func_trace), (param_types, return_type) in func_symbol_table.symbols.items():
            if func_trace == sub_trace:
                return func_name, (param_types, return_type)
    return None, None
    
def get_var_definition(var_symbol_table, var_name, scope_trace):
    for i in range(len(scope_trace), -1, -1):
        sub_trace = scope_trace[:i]
        var_type = var_symbol_table.get_type(var_name, sub_trace)
        if var_type is not None:
            return var_type
    return None

def get_func_definition(func_symbol_table, func_name, scope_trace):
    for i in range(len(scope_trace), -1, -1):
        sub_trace = scope_trace[:i]
        signature = func_symbol_table.get_signature(func_name, sub_trace)
        if signature is not None:
            return signature
    return None

def flatten_param_list_e(node):
    # <param_list_e> ::= <param_list> | <e> ;
    if get_node_name(node) == 'param_list':
        return flatten_param_list(node)
    else:
        return []
    
def flatten_param_list(node):
    # <param_list> ::= <param> | <param> "," <sep> <param_list> ;
    if len(node.children) == 1:
        return [node.children[0]]  # Single param
    else:
        return [node.children[0]] + flatten_param_list(node.children[3])  # param + param_list
    
def flatten_field_def_list_e(node):
    # <field_def_list_e> ::= <field_def_list> | <e> ;
    if get_node_name(node) == 'field_def_list':
        return flatten_field_def_list(node)
    else:
        return []
    
def flatten_field_def_list(node):
    # <field_def_list> ::= <ttype> <sep> <field_name> ";" | <ttype> <sep> <field_name> ";" "\n" <field_def_list> ;
    if len(node.children) == 4:
        return [node]  # Single field_def
    else:
        return node.children[0:3] + flatten_field_def_list(node.children[5])  # field_def + field_def_list

def flatten_expr_list_e(node):
    # <expr_list_e> ::= <expr_list> | <e> ;
    inner_node = node.children[0]
    if get_node_name(inner_node) == 'expr_list':
        return flatten_expr_list(inner_node)
    else:
        return []   
    
def flatten_expr_list(node):
    # <expr_list> ::= <expr> | <expr> "," "\n" <expr_list> ;
    if len(node.children) == 1:
        return [node.children[0]]  # Single expr
    else:
        return [node.children[0]] + flatten_expr_list(node.children[3])  # expr + expr_list

def flatten_fn_body_e(node):
    # <fn_body_e> ::= <statements> | <e> ;
    node_inner = node.children[0]
    if get_node_name(node_inner) == 'statements':
        return flatten_statements(node_inner)
    else:
        return []
    
def flatten_statements(node):
    # <statements> ::= <stmt> "\n" | <stmt> "\n" <statements> ;
    # node_inner = node.children[0]
    if len(node.children) == 2:
        return [node.children[0]]  # Single stmt
    else:
        return [node.children[0]] + flatten_statements(node.children[2])  # stmt + statements

#
# KeepReasonableStructVisitor
# Keep the number of structs reasonable.
# Current target: one struct, five fields max.
#
class KeepReasonableStructVisitor(DerivationTreeVisitor):
    def __init__(self):
        self.struct_count = 0
        self.field_count = 0
        self.violations = list()

    # <struct_def> ::= "struct" <sep> <struct_name> <sep> "{" "\n" <field_def_list_e> "\n" "}" ;
    def visit_struct_def(self, node):
        self.struct_count += 1
        if self.struct_count > 1:
            self.violations.append("struct")  # More than one struct defined
        # Visit children to count fields
        for child in node.children:
            self.generic_visit(child)

    # <field_def_list> ::= <type> <sep> <field_name> ";" | <type> <sep> <field_name> ";" "\n" <field_def_list> ;
    def visit_field_def_list(self, node):
        # Each field is a child of field_def_list
        for child in node.children:
            if get_node_name(child) == 'field_name':
                self.field_count += 1
                if self.field_count > 5:
                    self.violations.append("field")  # More than five fields defined

# Returns only in functions visitor.
class ConstraintVisitorReturnInFunc(DerivationTreeVisitor):
    def __init__(self):
        self.in_function = False
        self.violations = list()

    # <fn_def> ::= <ttype> <sep> <fn_kwd> <sep> <fn_name> "(" <param_list_e> ")" <sep> "{" <sep> <fn_body_e> <sep> "}" ;
    def visit_fn_def(self, node):
        self.in_function = True
        self.generic_visit(node)
        self.in_function = False

    # <return_stmt> ::= "return" <sep> <expr> ";" ;
    def visit_return_stmt(self, node):
        if not self.in_function:
            self.violations.append("return_outside_function")
        self.generic_visit(node)

# Builds the variable and function symbol tables, and also collects struct definitions.
class DeclarationCollector(DerivationTreeVisitor):
    def __init__(self):
        self.func_symbol_table = FuncSymbolTable()
        self.var_symbol_table = VarSymbolTable()
        self.struct_definitions = dict()  # struct_name -> list of (field_name, field_type)
        self.current_scope = []  # Stack to track current scope
        self.current_scope_id = 0
        # Will also track violations for: re-declared variables, structs, and functions
        self.violations = []

    # <decl> ::= <ttype> <sep> <var_name> <sep> <decl_rhs_e> ;
    def visit_decl(self, node):
        var_type = node.children[0].value()  # Assuming <ttype> is the first child
        var_name = node.children[2].value()  # Assuming <var_name> is the third child
        # Is name a reserved word?
        if var_name in C_RESERVED_WORDS:
            self.violations.append(f"reserved_word_{var_name}")
        # Check for re-declaration (at all)
        if get_var_definition(self.var_symbol_table, var_name, tuple(self.current_scope)) is not None:
            self.violations.append(f"redeclaration_var_{var_name}")
        self.var_symbol_table.define(var_name, tuple(self.current_scope), var_type)
        self.generic_visit(node)

    # <fn_def> ::= <ttype> <sep> <fn_kwd> <sep> <fn_name> "(" <param_list_e> ")" <sep> "{" <sep> <fn_body_e> <sep> "}" ;
    def visit_fn_def(self, node):
        return_type = node.children[0].value()  # Assuming <ttype> is the first child
        fn_name = node.children[4].value()  # Assuming <fn_name> is the fifth child
        # Is name a reserved word?
        if fn_name in C_RESERVED_WORDS:
            self.violations.append(f"reserved_word_{fn_name}")
        param_list_node = node.children[6]  # Assuming <param_list_e> is the seventh child
        param_types = []
        param_names = []
        
        # Extract parameters
        for param_node in flatten_param_list_e(param_list_node):
            param_type = param_node.children[0].value()  # <ttype>
            param_name = param_node.children[2].value()  # <param_name> -> <var_name>
            # Check if param name is a reserved word
            if param_name in C_RESERVED_WORDS:
                self.violations.append(f"reserved_word_{param_name}")
            param_types.append(param_type)
            param_names.append(param_name)
            # Define parameter in the current function scope
            self.var_symbol_table.define(param_name, tuple(self.current_scope + [self.current_scope_id + 1]), param_type)
        
        # Check if function already defined
        if get_func_definition(self.func_symbol_table, fn_name, tuple(self.current_scope)) is not None:
            self.violations.append(f"redeclaration_func_{fn_name}")

        # Define the function in the symbol table
        self.func_symbol_table.define(fn_name, tuple(self.current_scope), param_types, return_type)
        # Enter new function scope
        self.current_scope_id += 1
        self.current_scope.append(self.current_scope_id)
        self.generic_visit(node)
        self.current_scope.pop()

    # <struct_def> ::= "struct" <sep> <struct_name> <sep> "{" "\n" <field_def_list_e> "\n" "}" ;
    def visit_struct_def(self, node):
        struct_name = node.children[2].value()  # Assuming <struct_name> is the third child
        # Is name a reserved word?
        if struct_name in C_RESERVED_WORDS:
            self.violations.append(f"reserved_word_{struct_name}")
        field_def_list_node = node.children[5]  # Assuming <field_def_list_e> is the sixth child
        fields = []
        # <field_def_list_e> ::= <field_def_list> | <e> ;
        for field_node in flatten_field_def_list_e(field_def_list_node):
            field_type = field_node.children[0].value()  # <ttype>
            field_name = field_node.children[2].value()  # <field_name>
            fields.append((field_name, field_type))

        # Check for re-declaration of struct
        if struct_name in self.struct_definitions:
            self.violations.append(f"redeclaration_struct_{struct_name}")
        self.struct_definitions[struct_name] = fields
        self.generic_visit(node)

# Todo: Fix
class DefUseVisitor(DerivationTreeVisitor):
    def __init__(self):
        self.symbol_table = VarSymbolTable()
        self.function_table = FuncSymbolTable()
        self.struct_definitions = dict()  # struct_name -> list of (field_name, field_type)
        self.violations = []
        self.scope_trace = []  # Stack to track current scope
        self.scope_id = 0

    # <fn_def> ::= <ttype> <sep> <fn_kwd> <sep> <fn_name> "(" <param_list_e> ")" <sep> "{" <sep> <fn_body_e> <sep> "}" ;
    def visit_fn_def(self, node):
        # Enter new function scope
        self.scope_id += 1
        self.scope_trace.append(self.scope_id)
        self.generic_visit(node)
        self.scope_trace.pop()

    def visit_ttype(self, node):
        # If it's a struct type, check if it's defined
        type_name = node.children[0].value()  # Assuming <ttype> ::= <type> | <struct_name> ;
        if type_name not in ["int", "float", "double", "string", "bool", "void"] and type_name not in self.struct_definitions:
            self.violations.append(type_name)

    # <var_access> ::= <var_name> ;
    def visit_var_access(self, node):
        var_name = node.children[0].value()  # Assuming <var_name> is the first child
        # Use the name and scope to check if defined
        defined_type = get_var_definition(self.symbol_table, var_name, tuple(self.scope_trace))
        if defined_type is None:
            self.violations.append(var_name)
        self.generic_visit(node)

    # <assignment> ::= <var_access> <sep> <assign_op> <sep> <expr> ;
    def visit_assignment(self, node):
        var_name = node.children[0].children[0].value()  # Accessing <var_name> inside <var_access>
        defined_type = get_var_definition(self.symbol_table, var_name, tuple(self.scope_trace))
        if defined_type is None:
            self.violations.append(var_name)
        # Continue visiting children, but avoid double counting the var_access
        for child in node.children[1:]:
            self.visit(child)

# Field access validity visitor
class ConstraintVisitorStructAccess(DerivationTreeVisitor):
    def __init__(self):
        self.var_symbol_table = VarSymbolTable()
        self.struct_definitions = dict()  # struct_name -> list of (field_name, field_type)
        self.violations = []
        self.scope_trace = []  # Stack to track current scope
        self.scope_id = 0

    # Handle scope increases
    def visit_fn_def(self, node):
        # Enter new function scope
        self.scope_id += 1
        self.scope_trace.append(self.scope_id)
        self.generic_visit(node)
        self.scope_trace.pop()

    # <struct_def> ::= "struct" <sep> <struct_name> <sep> "{" "\n" <field_def_list_e> "\n" "}" ;
    # def visit_struct_def(self, node):
    # struct definitions should be initialized by a DeclarationCollector beforehand

    # <struct_access> ::= <var_name> "." <field_name> ;
    def visit_struct_access(self, node):
        var_access_node = node.children[0]
        field_name = node.children[2].value()  # Assuming <field_name> is the third child
        var_name = var_access_node.children[0].value()  # Accessing <var_name> inside <var_access>
        # Here we would need the type of var_name to check if it has field_name
        var_type = get_var_definition(self.var_symbol_table, var_name, tuple(self.scope_trace))
        if var_type is None:
            self.violations.append(var_name)  # Variable not defined
        elif var_type not in self.struct_definitions:
            self.violations.append(var_type)  # Variable type is not a struct
        else:
            fields = self.struct_definitions[var_type]
            if field_name not in [f[0] for f in fields]:
                self.violations.append(f"{var_name}.{field_name}")  # Field not found in struct
        self.generic_visit(node)

# No duplicate struct fields
class ConstraintVisitorNoDuplicateStructFields(DerivationTreeVisitor):
    def __init__(self):
        self.violations = []

    # <struct_def> ::= "struct" <sep> <struct_name> <sep> "{" "\n" <field_def_list_e> "\n" "}" ;
    def visit_struct_def(self, node):
        field_def_list_node = node.children[5]  # Assuming <field_def_list_e> is the sixth child
        field_names = set()
        for field_node in flatten_field_def_list_e(field_def_list_node):
            field_name = field_node.children[2].value()  # <field_name>
            if field_name in field_names:
                self.violations.append("duplicate_field")
            else:
                field_names.add(field_name)
        self.generic_visit(node)

# No void variables (void function returns ok)
class ConstraintVisitorNoVoidDecl(DerivationTreeVisitor):
    def __init__(self):
        self.violations = []

    # <decl> ::= <ttype> <sep> <var_name> <sep> <decl_rhs_e> ;
    def visit_decl(self, node):
        var_type = node.children[0].value()  # Assuming <ttype> is the first child
        if var_type == "void":
            self.violations.append("void_decl")
        self.generic_visit(node)

    # <param> ::= <ttype> <sep> <param_name> ;
    def visit_param(self, node):
        param_type = node.children[0].value()  # Assuming <ttype> is the first child
        if param_type == "void":
            self.violations.append("void_param")
        self.generic_visit(node)

    # <field_def_list> ::= <ttype> <sep> <field_name> ";" | <ttype> <sep> <field_name> ";" "\n" <field_def_list> ;
    def visit_field_def_list(self, node):
        flattened_def_list = flatten_field_def_list(node)
        for field_node in flattened_def_list:
            field_type = field_node.children[0].value()  # <ttype>
            if field_type == "void":
                self.violations.append("void_field")
        self.generic_visit(node)

# Struct exprs only in decls
class ConstraintVisitorStructExprRHSOfDecl(DerivationTreeVisitor):
    def __init__(self):
        self.violations = []
        self.in_decl = False

    # <decl> ::= <ttype> <sep> <var_name> <sep> <decl_rhs_e> ;
    def visit_decl(self, node):
        self.in_decl = True
        self.generic_visit(node)
        self.in_decl = False

    # <struct_expr> ::= "{" <field_init_list_e> "}" ;
    def visit_struct_expr(self, node):
        if not self.in_decl:
            self.violations.append("struct_expr_outside_decl")
        self.generic_visit(node)

# No empty structs
class ConstraintVisitorNoEmptyStruct(DerivationTreeVisitor):
    def __init__(self):
        self.violations = []

    # <struct_def> ::= "struct" <sep> <struct_name> <sep> "{" "\n" <field_def_list_e> "\n" "}" ;
    # <field_def_list_e> ::= <field_def_list> | <e> ;
    def visit_struct_def(self, node):
        # if field_def_list_e is <e>, then it's empty
        field_def_list_e_node = node.children[6]  # Assuming <field_def_list_e> is the sixth child
        if get_node_name(field_def_list_e_node.children[0]) == 'e':
            self.violations.append("empty_struct")
        self.generic_visit(node)

    # <struct_expr> ::= "{" "\n" <expr_list_e> "\n" "}" ;
    def visit_struct_expr(self, node):
        # if expr_list_e is <e>, then it's empty
        expr_list_e_node = node.children[2]  # Assuming <expr_list_e> is the third child
        if get_node_name(expr_list_e_node.children[0]) == 'e':
            self.violations.append("empty_struct_expr")
        self.generic_visit(node)

class TypeWrapper:
    def __init__(self, type_name, struct_fields=None, struct_fields_positional=None):
        self.type_name = type_name
        
        if struct_fields is not None:
            self.struct_fields = struct_fields  # dict of field_name -> field_type (TypeWrapper)
        else:
            self.struct_fields = dict()  # field_name -> field_type (TypeWrapper)
        
        if struct_fields_positional is not None:
            self.struct_fields_positional = struct_fields_positional  # list of (field_name, field_type) in order
        else:
            self.struct_fields_positional = []  # list of (field_name, field_type) in order

    def is_struct(self):
        return len(self.struct_fields) > 0 or len(self.struct_fields_positional) > 0

    def is_struct_positional(self):
        return len(self.struct_fields_positional) > 0
    
    def is_struct_named(self):
        return len(self.struct_fields) > 0

    def __str__(self):
        if self.is_struct():
            fields_str = ', '.join([f"{name}: {type.type_name}" for name, type in self.struct_fields_positional])
            return f"struct {{ {fields_str} }}"
        else:
            return self.type_name

def coercion_and_subtyping_possible(t1, t2):
    # if t1 and t2 are the same, return True
    if t1.type_name == t2.type_name:
        return True
    
    # if both are numeric types, return True
    numeric_types = ["int", "float", "double", "bool"]
    if t1.type_name in numeric_types and t2.type_name in numeric_types:
        return True
    
    # otherwise,
    return False

def types_compatible(t1, t2):
    # This handles exact matches and coercions/subtyping
    if coercion_and_subtyping_possible(t1, t2):
        return True

    # If both are structs, check field compatibility
    if t1.is_struct_named() and t2.is_struct_named():
        if len(t1.struct_fields) != len(t2.struct_fields):
            return False
        for field_name, field_type in t1.struct_fields.items():
            # get the field type in t2
            if field_name not in t2.struct_fields:
                return False
            if not types_compatible(field_type, t2.struct_fields[field_name]):
                return False
        return True
    
    # If both are positional structs, check field compatibility by position
    if t1.is_struct_positional() and t2.is_struct_positional():
        if len(t1.struct_fields_positional) != len(t2.struct_fields_positional):
            return False
        for (field_name1, field_type1), (field_name2, field_type2) in zip(t1.struct_fields_positional, t2.struct_fields_positional):
            if not types_compatible(field_type1, field_type2):
                return False
        return True
    
    # it is possible that one is named and one is positional
    if t1.is_struct() and t2.is_struct():
        positional_type = t1 if t1.is_struct_positional() else t2
        named_type = t2 if t1.is_struct_positional() else t1
        if len(positional_type.struct_fields_positional) != len(named_type.struct_fields):
            return False
        for (field_name, field_type), (named_field_name, named_field_type) in zip(positional_type.struct_fields_positional, named_type.struct_fields.items()):
            if not types_compatible(field_type, named_field_type):
                return False
        return True
    
    return False

def type_resulting_from_binop(op, t1, t2):
    # current binops are: <binop_op> ::= "+" | "-" | "/" | "*" | "%" | "^" | "==" | "!=" | "<=" | ">=" | "<" | ">" | "&&" | "||" 
    if op in ["+", "-", "/", "*"]:
        if t1.type_name in ["int", "float", "double"] and t2.type_name in ["int", "float", "double"]:
            # Result type is the more general of the two
            if t1.type_name == "double" or t2.type_name == "double":
                return TypeWrapper("double")
            elif t1.type_name == "float" or t2.type_name == "float":
                return TypeWrapper("float")
            else:
                return TypeWrapper("int")
        else:
            return None  # Invalid types for arithmetic
    elif op in ["%", "^"]:
        if t1.type_name in ["int", "bool"] and t2.type_name in ["int", "bool"]:
            return TypeWrapper("int")
        else:
            return None  # Invalid types for modulus or exponentiation
    elif op in ["==", "!=", "<=", ">=", "<", ">"]:
        if coercion_and_subtyping_possible(t1, t2):
            return TypeWrapper("bool")
        else:
            return None  # Invalid types for comparison
    elif op in ["&&", "||"]:
        if t1.type_name == "bool" and t2.type_name == "bool":
            return TypeWrapper("bool")
        else:
            return None  # Invalid types for logical operations

def type_resulting_from_unop(op, t):
    # current unops are: <unop_op> ::= "-" | "!" ;
    if op == "-":
        if t.type_name in ["int", "float", "double", "bool"]:
            return t  # Negation keeps the same numeric type
        else:
            return None  # Invalid type for negation
    elif op == "!":
        if t.type_name in ["bool", "int", "float", "double"]:
            return TypeWrapper("bool")
        else:
            return None  # Invalid type for logical NOT

def infer_expr_type_unit(node, var_symbol_table, func_symbol_table, struct_definitions, scope_trace):
    # <expr_unit> ::= <var_access> | <value> | <fn_call> | <struct_expr> | <struct_access> ;
    child = node.children[0]
    if get_node_name(child) == 'var_access':
        var_name = child.children[0].value()  # Assuming <var_name> is the first child
        var_type_name = get_var_definition(var_symbol_table, var_name, tuple(scope_trace))
        if var_type_name is None:
            return None  # Variable not defined
        if var_type_name in struct_definitions:
            fields = struct_definitions[var_type_name]
            field_dict = {name: TypeWrapper(type_name) for name, type_name in fields}
            return TypeWrapper(var_type_name, struct_fields=field_dict, struct_fields_positional=fields)
        else:
            return TypeWrapper(var_type_name)
    elif get_node_name(child) == 'value':
        # <value> ::= <bool_val> | <num_val> | <string_val> ;
        # <num_val> ::= <int> | <float> | <double> ;
        val_child = child.children[0]
        if get_node_name(val_child) == 'bool_val':
            return TypeWrapper("bool")
        elif get_node_name(val_child) == 'num_val':
            num_child = val_child.children[0]
            if get_node_name(num_child) == 'int':
                return TypeWrapper("int")
            elif get_node_name(num_child) == 'float':
                return TypeWrapper("float")
            elif get_node_name(num_child) == 'double':
                return TypeWrapper("double")
        elif get_node_name(val_child) == 'string_val':
            return TypeWrapper("char")
        else:
            return None  # Unknown value type
    elif get_node_name(child) == 'fn_call':
        fn_name = child.children[0].value()  # Assuming <fn_name> is the first child
        signature = get_func_definition(func_symbol_table, fn_name, tuple(scope_trace))
        if signature is None:
            return None  # Function not defined
        param_types, return_type = signature
        return TypeWrapper(return_type)
    elif get_node_name(child) == 'struct_expr':
        # <struct_expr> ::= "{" "\n" <expr_list_e> "\n" "}" ;
        # <expr_list_e> ::= <expr_list> | <e> ;
        # <expr_list> ::= <expr> | <expr> "," "\n" <expr_list> ;
        expr_list_e_node = child.children[2]  # Assuming <expr_list_e> is the third child
        expr_nodes = flatten_expr_list_e(expr_list_e_node)
        field_types = []
        for expr_node in expr_nodes:
            expr_type = infer_expr_type(expr_node, var_symbol_table, func_symbol_table, struct_definitions, scope_trace)
            if expr_type is None:
                return None  # Unable to infer type of an expression
            field_types.append((None, expr_type))  # Field names are None for positional structs
        return TypeWrapper("struct", struct_fields_positional=field_types)
    elif get_node_name(child) == 'struct_access':
        # <struct_access> ::= <var_name> "." <field_name> ;
        var_access_node = child.children[0]
        field_name = child.children[2].value()  # Assuming <field_name> is the third child
        var_name = var_access_node.children[0].value()  # Accessing <var_name> inside <var_access>
        var_type_name = get_var_definition(var_symbol_table, var_name, tuple(scope_trace))
        if var_type_name is None:
            return None  # Variable not defined
        if var_type_name not in struct_definitions:
            return None  # Variable type is not a struct
        fields = struct_definitions[var_type_name]
        field_dict = {name: TypeWrapper(type_name) for name, type_name in fields}
        if field_name not in field_dict:
            return None  # Field not found in struct
        return field_dict[field_name]
    else:
        return None  # Unknown expr_unit type    

def infer_expr_type(node, var_symbol_table, func_symbol_table, struct_definitions, scope_trace):
    # <expr> ::= <arith_expr> | <expr_unit> ;
    # <arith_expr> ::= <binop> | <unop> ;
    # <binop> ::= <expr_unit> <sep> <binop_op> <sep> <expr> ;
    # <unop> ::= <unop_op> <expr> ;
    inner_node = node.children[0]
    if get_node_name(inner_node) == 'expr_unit':
        return infer_expr_type_unit(inner_node, var_symbol_table, func_symbol_table, struct_definitions, scope_trace)
    elif get_node_name(inner_node) == 'arith_expr':
        inner_node = inner_node.children[0]  # either <unop> or <binop>
        if get_node_name(inner_node) == "unop":
            # Unary operation
            # <unop> ::= <unop_op> <expr> ;
            op = inner_node.children[0].value()  # <unop_op>
            expr_node = inner_node.children[1]  # <expr>
            expr_type = infer_expr_type(expr_node, var_symbol_table, func_symbol_table, struct_definitions, scope_trace)
            if expr_type is None:
                return None
            return type_resulting_from_unop(op, expr_type)
        elif get_node_name(inner_node) == "binop":
            # Binary operation
            left_node = inner_node.children[0]  # <expr_unit>
            op = inner_node.children[2].value()  # <binop_op>
            right_node = inner_node.children[4]  # <expr>
            left_type = infer_expr_type_unit(left_node, var_symbol_table, func_symbol_table, struct_definitions, scope_trace)
            right_type = infer_expr_type(right_node, var_symbol_table, func_symbol_table, struct_definitions, scope_trace)
            if left_type is None or right_type is None:
                return None
            return type_resulting_from_binop(op, left_type, right_type)
        else:
            return None  # Invalid arith_expr structure
    else:
        print("Unknown expr type:", inner_node)
        return None  # Unknown expr type

# TypeCheckingVisitor
class ConstraintVisitorTypeCheck(DerivationTreeVisitor):
    def __init__(self):
        self.var_symbol_table = VarSymbolTable()
        self.function_table = FuncSymbolTable()
        self.struct_definitions = dict()  # struct_name -> list of (field_name, field_type)
        self.violations = []
        self.scope_trace = []  # Stack to track current scope
        self.scope_id = 0

    # Handle scope increases
    def visit_fn_def(self, node):
        # Enter new function scope
        self.scope_id += 1
        self.scope_trace.append(self.scope_id)

        # Handle returns
        # <fn_def> ::= <ttype> <sep> <fn_kwd> <sep> <fn_name> "(" <param_list_e> ")" <sep> "{" <sep> <fn_body_e> <sep> "}" ;
        return_type = node.children[0].value()  # Assuming <ttype> is the first child
        # All param stuff handled in DeclarationCollector
        # For now, look only at return statements in the body
        fn_body_node = node.children[11]  # Assuming <fn_body_e> is where it is
        flattened_body = flatten_fn_body_e(fn_body_node)
        for stmt in flattened_body:
            if get_node_name(stmt) == 'return_stmt':
                # get inner node
                inner_node = stmt.children[0] # <return_stmt> ::= <return_kwd> | <return_kwd> <sep> <expr> ;
                # if it's just <return_kwd>, then it's a void return
                if len(inner_node.children) == 1:
                    if return_type != "void":
                        self.violations.append(f"return_type_mismatch: expected {return_type}, got void")
                    continue
                # otherwise, it's <return_kwd> <sep> <expr>
                expr_node = inner_node.children[2]  # <expr>
                expr_type = infer_expr_type(expr_node, self.var_symbol_table, self.function_table, self.struct_definitions, self.scope_trace + [self.scope_id])
                if expr_type is None:
                    self.violations.append("unable_to_infer_return_type")
                else:
                    expected_return_type = TypeWrapper(return_type)
                    if return_type in self.struct_definitions:
                        fields = self.struct_definitions[return_type]
                        field_dict = {name: TypeWrapper(type_name) for name, type_name in fields}
                        expected_return_type = TypeWrapper(return_type, struct_fields=field_dict, struct_fields_positional=fields)
                    if not types_compatible(expr_type, expected_return_type):
                        self.violations.append(f"return_type_mismatch: expected {expected_return_type}, got {expr_type}")
        
        # handle case when no return statement in function with non-void return type
        if return_type != "void":
            has_return = any(get_node_name(stmt) == 'return_stmt' for stmt in flattened_body)
            if not has_return:
                self.violations.append("missing_return_statement")

        self.generic_visit(node)
        self.scope_trace.pop()

    # <assignment> ::= <var_access> <sep> <assign_op> <sep> <expr> ;
    def visit_assignment(self, node):
        var_access_node = node.children[0]
        expr_node = node.children[4]
        var_name = var_access_node.children[0].value()  # Accessing <var_name> inside <var_access>
        var_type_name = get_var_definition(self.var_symbol_table, var_name, tuple(self.scope_trace))
        if var_type_name is None:
            self.violations.append(var_name)  # Variable not defined
        else:
            var_type = TypeWrapper(var_type_name)
            if var_type_name in self.struct_definitions:
                fields = self.struct_definitions[var_type_name]
                field_dict = {name: TypeWrapper(type_name) for name, type_name in fields}
                var_type = TypeWrapper(var_type_name, struct_fields=field_dict, struct_fields_positional=fields)
            expr_type = infer_expr_type(expr_node, self.var_symbol_table, self.function_table, self.struct_definitions, self.scope_trace)
            if expr_type is None:
                self.violations.append("unable_to_infer_expr_type")
            else:
                if not types_compatible(expr_type, var_type):
                    self.violations.append(f"assignment_type_mismatch: variable {var_name} of type {var_type}, assigned expression of type {expr_type}")
        self.generic_visit(node)

    # <decl> ::= <ttype> <sep> <var_name> <sep> <decl_rhs_e> ;
    def visit_decl(self, node):
        var_type_name = node.children[0].value()  # Assuming <ttype> is the first child
        var_name = node.children[2].value()  # Assuming <var_name> is the third child
        decl_rhs_node = node.children[4].children[0]  # <decl_rhs> or <e>
        if get_node_name(decl_rhs_node) != 'e':
            # <decl_rhs_e> ::= <decl_rhs> | <e> ;
            # <decl_rhs> ::= "=" <sep> <expr> ;
            expr_node = decl_rhs_node.children[2]  # <expr>
            expr_type = infer_expr_type(expr_node, self.var_symbol_table, self.function_table, self.struct_definitions, self.scope_trace)
            if expr_type is None:
                self.violations.append("unable_to_infer_decl_rhs_type")
            else:
                var_type = TypeWrapper(var_type_name)
                if var_type_name in self.struct_definitions:
                    fields = self.struct_definitions[var_type_name]
                    field_dict = {name: TypeWrapper(type_name) for name, type_name in fields}
                    var_type = TypeWrapper(var_type_name, struct_fields=field_dict, struct_fields_positional=fields)
                if not types_compatible(expr_type, var_type):
                    self.violations.append(f"decl_assignment_type_mismatch: variable {var_name} of type {var_type}, assigned expression of type {expr_type}")
        self.generic_visit(node)

    # <return> ::= <sep> <expr> <sep> ;
    def visit_return_stmt(self, node):
        # Handled in visit_fn_def
        self.generic_visit(node)

    # <expr_stmt> ::= <expr> ";" ;
    def visit_expr_stmt(self, node):
        expr_node = node.children[0]  # <expr>
        expr_type = infer_expr_type(expr_node, self.var_symbol_table, self.function_table, self.struct_definitions, self.scope_trace)
        if expr_type is None:
            self.violations.append("unable_to_infer_expr_stmt_type")
        self.generic_visit(node)

    # <struct_expr> ::= "{" "\n" <expr_list_e> "\n" "}" ;
    def visit_struct_expr(self, node):
        # this gets type checked elsewhere (in infer_expr_type_unit), but it's
        # a superficial check that doesn't see how much of the content type checks.
        # here, we want to collect all issues inside the struct expr, and register
        # violations for each.
        flattened_struct_content = flatten_expr_list_e(node.children[2])  # <expr_list_e> is the third child
        for expr in flattened_struct_content:
            expr_type = infer_expr_type(expr, self.var_symbol_table, self.function_table, self.struct_definitions, self.scope_trace)
            if expr_type is None:
                self.violations.append("unable_to_infer_struct_expr_type")
            # Additional checks for struct fields can be added here
        self.generic_visit(node)

##
#
# Constraints to ensure sizable inputs.
#
##
class NodeGoalVisitor(DerivationTreeVisitor):
    def __init__(self):
        self.node_count = 0

    def generic_visit(self, node):
        self.node_count += 1
        for child in getattr(node, 'children', []):
            self.visit(child)

def num_violations_validity_only(tree, should_print = False):

    # Actual constraints visitors

    # decl collector
    declaration_collector = DeclarationCollector()
    declaration_collector.visit(tree)

    if should_print:
        print("=== Declaration Collector ===")
        print("Variable Symbol Table:")
        for (var_name, scope), var_type in declaration_collector.var_symbol_table.symbols.items():
            print(f"  {var_name} @ {scope}: {var_type}")
        print("Function Symbol Table:")
        for (func_name, scope), (param_types, return_type) in declaration_collector.func_symbol_table.symbols.items():
            print(f"  {func_name} @ {scope}: params {param_types} -> {return_type}")
        print("Struct Definitions:")
        for struct_name, fields in declaration_collector.struct_definitions.items():
            field_str = ', '.join([f"{name}: {type}" for name, type in fields])
            print(f"  {struct_name}: {field_str}")
        # Also print any violations found during declaration collection
        for var in declaration_collector.violations:
            print(f"Violation: {var}")

    # def-use
    def_use_visitor = DefUseVisitor()
    def_use_visitor.symbol_table = declaration_collector.var_symbol_table
    def_use_visitor.function_table = declaration_collector.func_symbol_table
    def_use_visitor.struct_definitions = declaration_collector.struct_definitions
    def_use_visitor.visit(tree)

    if should_print:
        print("=== Def-Use Visitor ===")
        for var in def_use_visitor.violations:
            print(f"Violation: {var}")

    # return only in functions
    return_in_func_visitor = ConstraintVisitorReturnInFunc()
    return_in_func_visitor.visit(tree)

    if should_print:
        print("=== Return In Function Visitor ===")
        for var in return_in_func_visitor.violations:
            print(f"Violation: {var}")

    # no duplicate struct fields
    no_duplicate_struct_fields_visitor = ConstraintVisitorNoDuplicateStructFields()
    no_duplicate_struct_fields_visitor.visit(tree)  

    if should_print:
        print("=== No Duplicate Struct Fields Visitor ===")
        for var in no_duplicate_struct_fields_visitor.violations:
            print(f"Violation: {var}")

    # struct field access
    struct_access_visitor = ConstraintVisitorStructAccess()
    struct_access_visitor.var_symbol_table = declaration_collector.var_symbol_table
    struct_access_visitor.struct_definitions = declaration_collector.struct_definitions
    struct_access_visitor.visit(tree)

    if should_print:
        print("=== Struct Access Visitor ===")
        for var in struct_access_visitor.violations:
            print(f"Violation: {var}")

    # no void decls
    no_void_decl_visitor = ConstraintVisitorNoVoidDecl()
    no_void_decl_visitor.visit(tree)

    if should_print:
        print("=== No Void Declarations Visitor ===")
        for var in no_void_decl_visitor.violations:
            print(f"Violation: {var}")

    # struct expr only in decls
    struct_expr_rhs_of_decl_visitor = ConstraintVisitorStructExprRHSOfDecl()
    struct_expr_rhs_of_decl_visitor.visit(tree)

    if should_print:
        print("=== Struct Expr RHS Of Decl Visitor ===")
        for var in struct_expr_rhs_of_decl_visitor.violations:
            print(f"Violation: {var}")

    # no empty structs
    no_empty_struct_visitor = ConstraintVisitorNoEmptyStruct()
    no_empty_struct_visitor.visit(tree)

    if should_print:
        print("=== No Empty Struct Visitor ===")
        for var in no_empty_struct_visitor.violations:
            print(f"Violation: {var}")

    # type checking
    type_check_visitor = ConstraintVisitorTypeCheck()
    try:
        type_check_visitor.var_symbol_table = declaration_collector.var_symbol_table
        type_check_visitor.function_table = declaration_collector.func_symbol_table
        type_check_visitor.struct_definitions = declaration_collector.struct_definitions
        type_check_visitor.visit(tree)
    except Exception as e:
        # print the traceback
        traceback.print_exc()   

    if should_print:
        print("=== Type Check Visitor ===")
        for var in type_check_visitor.violations:
            print(f"Violation: {var}")

    # For debugging, just return 0 so we can look and see
    # what the counts are
    # return 0

    # Try just the node goal visitor
    # This will never produce anything.
    # return 1 if node_goal_visitor.node_count < 1000 else 0

    # Return number of violations
    return len(def_use_visitor.violations) + \
           len(return_in_func_visitor.violations) + \
           len(struct_access_visitor.violations) + \
           len(no_void_decl_visitor.violations) + \
           len(struct_expr_rhs_of_decl_visitor.violations) + \
           len(no_empty_struct_visitor.violations) + \
           len(type_check_visitor.violations) + \
           len(declaration_collector.violations) + \
           len(no_duplicate_struct_fields_visitor.violations)

class SizeConstraintVisitor(DerivationTreeVisitor):
    def __init__(self):
        self.struct_count = 0
        self.function_count = 0
        self.statement_count = 0
        self.violations = []

    # <struct_def> ::= "struct" <sep> <struct_name> <sep> "{" "\n" <field_def_list_e> "\n" "}" ;
    def visit_struct_def(self, node):
        self.struct_count += 1
        if self.struct_count > 1:
            self.violations.append("too_many_structs")
        self.generic_visit(node)

    # <fn_def> ::= <ttype> <sep> <fn_kwd> <sep> <fn_name> "(" <param_list_e> ")" <sep> "{" <sep> <fn_body_e> <sep> "}" ;
    def visit_fn_def(self, node):
        self.function_count += 1
        if self.function_count > 1:
            self.violations.append("too_many_functions")
        self.generic_visit(node)

    # <stmt> ::= <decl> | <assignment> | <fn_call_stmt> | <return_stmt> | <expr_stmt> ;
    def visit_stmt(self, node):
        self.statement_count += 1
        self.generic_visit(node)

# Constraints for the lang grammar.
def num_violations_size_and_validity(tree, should_print = False):

    # First, goal visitors.
    # node_goal_visitor = NodeGoalVisitor()
    # node_goal_visitor.visit(tree)
    # if should_print:
    #     print("=== Node Goal Visitor ===")
    #     print("Node Count:", node_goal_visitor.node_count)

    reasonable_size_visitor = SizeConstraintVisitor()
    reasonable_size_visitor.visit(tree)

    if should_print:
        print("=== Reasonable Size Visitor ===")
        print("Struct Count:", reasonable_size_visitor.struct_count)
        print("Function Count:", reasonable_size_visitor.function_count)
        print("Statement Count:", reasonable_size_visitor.statement_count)
        for var in reasonable_size_visitor.violations:
            print(f"Violation: {var}")

    # If there aren't enough statements, register another violation
    if reasonable_size_visitor.statement_count < 5:
        reasonable_size_visitor.violations.append("too_few_statements")

    # Actual constraints visitors

    # decl collector
    declaration_collector = DeclarationCollector()
    declaration_collector.visit(tree)

    if should_print:
        print("=== Declaration Collector ===")
        print("Variable Symbol Table:")
        for (var_name, scope), var_type in declaration_collector.var_symbol_table.symbols.items():
            print(f"  {var_name} @ {scope}: {var_type}")
        print("Function Symbol Table:")
        for (func_name, scope), (param_types, return_type) in declaration_collector.func_symbol_table.symbols.items():
            print(f"  {func_name} @ {scope}: params {param_types} -> {return_type}")
        print("Struct Definitions:")
        for struct_name, fields in declaration_collector.struct_definitions.items():
            field_str = ', '.join([f"{name}: {type}" for name, type in fields])
            print(f"  {struct_name}: {field_str}")
        # Also print any violations found during declaration collection
        for var in declaration_collector.violations:
            print(f"Violation: {var}")

    # def-use
    def_use_visitor = DefUseVisitor()
    def_use_visitor.symbol_table = declaration_collector.var_symbol_table
    def_use_visitor.function_table = declaration_collector.func_symbol_table
    def_use_visitor.struct_definitions = declaration_collector.struct_definitions
    def_use_visitor.visit(tree)

    if should_print:
        print("=== Def-Use Visitor ===")
        for var in def_use_visitor.violations:
            print(f"Violation: {var}")

    # return only in functions
    return_in_func_visitor = ConstraintVisitorReturnInFunc()
    return_in_func_visitor.visit(tree)

    if should_print:
        print("=== Return In Function Visitor ===")
        for var in return_in_func_visitor.violations:
            print(f"Violation: {var}")

    # no duplicate struct fields
    no_duplicate_struct_fields_visitor = ConstraintVisitorNoDuplicateStructFields()
    no_duplicate_struct_fields_visitor.visit(tree)

    # struct field access
    struct_access_visitor = ConstraintVisitorStructAccess()
    struct_access_visitor.var_symbol_table = declaration_collector.var_symbol_table
    struct_access_visitor.struct_definitions = declaration_collector.struct_definitions
    struct_access_visitor.visit(tree)

    if should_print:
        print("=== Struct Access Visitor ===")
        for var in struct_access_visitor.violations:
            print(f"Violation: {var}")

    # no void decls
    no_void_decl_visitor = ConstraintVisitorNoVoidDecl()
    no_void_decl_visitor.visit(tree)

    if should_print:
        print("=== No Void Declarations Visitor ===")
        for var in no_void_decl_visitor.violations:
            print(f"Violation: {var}")

    # struct expr only in decls
    struct_expr_rhs_of_decl_visitor = ConstraintVisitorStructExprRHSOfDecl()
    struct_expr_rhs_of_decl_visitor.visit(tree)

    if should_print:
        print("=== Struct Expr RHS Of Decl Visitor ===")
        for var in struct_expr_rhs_of_decl_visitor.violations:
            print(f"Violation: {var}")

    # no empty structs
    no_empty_struct_visitor = ConstraintVisitorNoEmptyStruct()
    no_empty_struct_visitor.visit(tree)

    if should_print:
        print("=== No Empty Struct Visitor ===")
        for var in no_empty_struct_visitor.violations:
            print(f"Violation: {var}")

    # type checking
    type_check_visitor = ConstraintVisitorTypeCheck()
    try:
        type_check_visitor.var_symbol_table = declaration_collector.var_symbol_table
        type_check_visitor.function_table = declaration_collector.func_symbol_table
        type_check_visitor.struct_definitions = declaration_collector.struct_definitions
        type_check_visitor.visit(tree)
    except Exception as e:
        # print the traceback
        traceback.print_exc()   

    if should_print:
        print("=== Type Check Visitor ===")
        for var in type_check_visitor.violations:
            print(f"Violation: {var}")

    # For debugging, just return 0 so we can look and see
    # what the counts are
    # return 0

    # Try just the node goal visitor
    # This will never produce anything.
    # return 1 if node_goal_visitor.node_count < 1000 else 0

    # Return number of violations
    return len(reasonable_size_visitor.violations) + \
           len(def_use_visitor.violations) + \
           len(return_in_func_visitor.violations) + \
           len(struct_access_visitor.violations) + \
           len(no_void_decl_visitor.violations) + \
           len(struct_expr_rhs_of_decl_visitor.violations) + \
           len(no_empty_struct_visitor.violations) + \
           len(type_check_visitor.violations) + \
           len(declaration_collector.violations) + \
           len(no_duplicate_struct_fields_visitor.violations)