[package]
name = "fandango"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
fandango-core = { path = "core" }
fandango-derive = { path = "derive" }

pest.workspace = true
pest_derive.workspace = true

[dev-dependencies]
petgraph.workspace = true

[lints]
workspace = true

[workspace]
members = [".", "core", "derive", "generator"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
authors = ["Addison Crump <addison.crump@cispa.de>"]

[workspace.dependencies]
pest = "2.7"
pest_derive = "2.7"
pest_generator = "2.7"
petgraph = "0.6.5"
proc-macro2 = "1.0"
quote = "1.0"
rand_core = "0.6.4"
syn = "2.0"

[workspace.lints.rust]
bindings_with_variant_name = "allow"
missing_docs = "warn"
