[package]
name = "fandango"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
fandango-core = { path = "core" }
fandango-derive = { path = "derive" }

pest.workspace = true
pest_derive.workspace = true
tuple_list.workspace = true

[dev-dependencies]
fandango-core = { path = "core", features = ["std", "dynamic"] }

criterion.workspace = true
rand = { workspace = true, features = ["default"] }

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
inherits = "release"
debug = true

[lints]
workspace = true

[workspace]
members = [".", "core", "derive", "generator"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Addison Crump <addison.crump@cispa.de>"]

[workspace.dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
either = { version = "1.13", default-features = false }
embedded-io = { version = "0.6.1", features = ["alloc"] }
hashbrown = "0.15.2"
pest = { version = "2.7", default-features = false }
pest_derive = { version = "2.7", default-features = false }
pest_generator = { version = "2.7", default-features = false }
petgraph = "0.7.1"
proc-macro2 = "1.0"
quote = "1.0"
rand = { version = "0.9.0", default-features = false }
syn = "2.0"
tuple_list = "0.1.3"

[workspace.lints.rust]
bindings_with_variant_name = "allow"
type_alias_bounds = "allow"

missing_docs = "warn"

[[bench]]
name = "generation"
path = "benches/generate.rs"
harness = false

[[bench]]
name = "bytegen"
path = "benches/bytegen.rs"
harness = false
