[package]
name = "fandango-runtime"
description = "Generic runtime support for fandango-rs."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
fandango = { path = ".." }

anyhow.workspace = true
either.workspace = true
hashbrown.workspace = true
mappable-rc.workspace = true
num-rational.workspace = true

[lints]
workspace = true
