[package]
name = "fandango-eval"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[features]
default = ["csv", "rest", "scriptsizec", "xml"]

csv = []
rest = []
scriptsizec = []
xml = []

[dev-dependencies]
rand = { workspace = true, features = ["default"] }

[dependencies]
fandango = { path = ".." }

embedded-io.workspace = true
hashbrown.workspace = true
petgraph.workspace = true

[lints]
workspace = true
