fandango = { SOI ~ program ~ EOI }

program = { NEWLINE* ~ (statement ~ NEWLINE*)* }

statement = { production }

// expression is not yet supported
production = {
  (
    nonterminal ~ "::=" ~ alternative ~ ";"
  )
}

nonterminal = { "<" ~ name ~ ">" }
name = { XID_START ~ XID_CONTINUE* }

alternative = { concatenation ~ ( "|" ~ concatenation )* }

concatenation = { operator ~ ( operator )* }

operator = {
  kleene
| plus
| option
| repeat
| symbol
}

// char_set is currently ambiguous and therefore omitted
symbol = {
  (
    nonterminal
  | string
  | bytes
  | "(" ~ alternative ~ ")"
  )
}

kleene = { symbol ~ "*" }
plus   = { symbol ~ "+" }
option = { symbol ~ "?" }
repeat = {
  ( symbol ~ "{" ~ integer ~ "}" )
| ( symbol ~ "{" ~ integer ~ "," ~ integer ~ "}" )
}

constraint = { "" }

WHITESPACE = _{ PATTERN_WHITE_SPACE }
