[package]
name = "fandango-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
std = ["petgraph"]
dynamic = []

[dependencies]
either.workspace = true
embedded-io.workspace = true
hashbrown.workspace = true
pest.workspace = true
pest_derive.workspace = true
petgraph = { workspace = true, optional = true }
rand.workspace = true
tuple_list.workspace = true

[lints]
workspace = true