[package]
name = "fandango-core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
either.workspace = true
pest.workspace = true
pest_derive.workspace = true
petgraph.workspace = true
rand.workspace = true
tuple_list.workspace = true

[lints]
workspace = true