[package]
name = "xml"
version = "0.0.0"
edition = "2024"
publish = false

[features]
static_defs = ["common/static_defs", "fandango-targets/static_defs"]

[dependencies]
fandango.workspace = true
fandango-targets = { workspace = true, features = ["xml"] }

common = { path = "../common" }

[lints]
workspace = true