//! Generator routines for FANDANGO. See [`Generated::generate`] for details on how to use them.

pub mod util;

use crate::dynamic::DefinitionOf;
use crate::lang::FandangoNode;
use crate::typing::AsStaticNode;
use alloc::boxed::Box;
use rand::{Rng, SeedableRng};

/// Sampler which is not associated with any particular node.
pub trait RawSampler {
    /// Sample an arbitrary usize, without any tagging information.
    fn sample(&mut self) -> usize;

    /// Resets the seed with the provided value.
    fn reseed(&mut self, seed: u64);
}

/// Sampler definition, allowing for tuning of the random generation. See [`util::Flattener`]'s
/// source code for an example of how this might be used.
pub trait Sampler<N>: RawSampler {
    /// Sample a kleene operator for a number of repetitions.
    fn sample_kleene(&mut self) -> usize;
    /// Sample a plus operator for a number of repetitions.
    fn sample_plus(&mut self) -> usize;
    /// Sample an optional operator to determine if the child is generated.
    fn sample_optional(&mut self) -> bool;
    /// Sample from a range of repetitions.
    fn sample_repetition(&mut self, lower: usize, upper: usize) -> usize;
    /// Sample over an alternative.
    fn sample_alternative(&mut self, count: usize) -> usize;
}

/// The default upper bound on the number of repetitions when an unmodified [`Rng`] is used as a
/// [`Sampler`].
pub const DEFAULT_UPPER_COUNT: usize = 5;

impl<R> RawSampler for R
where
    R: Rng + SeedableRng,
{
    #[allow(clippy::cast_possible_truncation)]
    fn sample(&mut self) -> usize {
        self.next_u64() as usize
    }

    fn reseed(&mut self, seed: u64) {
        *self = R::seed_from_u64(seed);
    }
}

impl<N, R> Sampler<N> for R
where
    R: Rng + SeedableRng,
{
    fn sample_kleene(&mut self) -> usize {
        self.random_range(0..DEFAULT_UPPER_COUNT)
    }

    fn sample_plus(&mut self) -> usize {
        self.random_range(1..DEFAULT_UPPER_COUNT)
    }

    fn sample_optional(&mut self) -> bool {
        self.random()
    }

    fn sample_repetition(&mut self, lower: usize, upper: usize) -> usize {
        self.random_range(lower..=upper)
    }

    fn sample_alternative(&mut self, count: usize) -> usize {
        self.random_range(0..count)
    }
}

impl<N, R> DefinitionOf<N> for R
where
    N: AsStaticNode,
    R: Rng,
{
    fn root_of(&self) -> FandangoNode<'static, 'static> {
        N::static_root()
    }

    fn definition_of(&self) -> FandangoNode<'static, 'static> {
        N::static_definition()
    }
}

/// Indicates that a node has a default generation strategy.
pub trait DefaultGenerated<S, G> {
    /// Generate this node using the default strategy, and generate any children with [`G`].
    fn generate_default(sampler: &mut S, with: &mut G, depth: usize) -> Self;
}

impl<N, S, G> DefaultGenerated<S, G> for Box<N>
where
    N: DefaultGenerated<S, G>,
{
    fn generate_default(sampler: &mut S, with: &mut G, depth: usize) -> Self {
        Box::new(N::generate_default(sampler, with, depth))
    }
}

/// Indicates that a node may be generated by a specific generator.
pub trait Generated<S, G> {
    /// Generates a node using [`G`], falling back to the default generator if it fails.
    ///
    /// The [`G`] parameter, for automatic implementations, must implement [`GeneratorTuple`]. This
    /// tuple may be created with [`tuple_list::tuple_list`], in order of application. When a
    /// generator is in use (i.e. generating a parent node), the children nodes cannot be generated
    /// with that generator. TODO check if this possible; this currently infinite-loops rustc.
    ///
    /// For similar reasons, this includes when parent generators fail. TODO this should be fixable.
    fn generate(sampler: &mut S, with: &mut G, depth: usize) -> Self;
}

impl<N, S, G> Generated<S, G> for N
where
    N: DefaultGenerated<S, G>,
    G: GeneratorTuple<N, S>,
{
    fn generate(sampler: &mut S, with: &mut G, depth: usize) -> Self {
        with.generate(sampler, depth)
            .unwrap_or_else(|| N::generate_default(sampler, with, depth))
    }
}

/// Generates a node in place, for use with [`super::visitor::Visitor`]s.
pub trait InPlaceGenerated<S, G> {
    /// Generates and replaces the contained node in-place, returning the new node.
    fn generate_in_place(&mut self, sampler: &mut S, with: &mut G, depth: usize);
}

/// Primary generator trait, for defining generators. You almost certainly only want to implement
/// this; see [`util::Flattener`] for inspiration.
pub trait Generator<N, W, S> {
    /// Attempt to generate the input.
    ///
    /// Minor footgun note: If you e.g. modify the sampler to be used by the remaining generators,
    /// you then need to make sure to call [`Generated::generate`] with the remaining generators
    /// provided in [`W`]. Do *NOT* call [`GeneratorTuple::generate`] to do so, as this will not
    /// pass your sampler to the default generator.
    fn generate(&mut self, sampler: &mut S, with: &mut W, depth: usize) -> Option<N>;
}

/// A list of generators, processed in order. Use [`tuple_list::tuple_list`] to create one from a
/// list of existing generators.
pub trait GeneratorTuple<N, S> {
    /// Attempt to generate a node [`N`] using the available generators.
    fn generate(&mut self, sampler: &mut S, depth: usize) -> Option<N>;
}

impl<Head, Tail, N, S> GeneratorTuple<N, S> for (Head, Tail)
where
    Head: Generator<N, Tail, S>,
    Tail: GeneratorTuple<N, S>,
{
    fn generate(&mut self, sampler: &mut S, depth: usize) -> Option<N> {
        self.0
            .generate(sampler, &mut self.1, depth)
            .or_else(|| self.1.generate(sampler, depth))
    }
}

impl<N, S> GeneratorTuple<N, S> for () {
    fn generate(&mut self, _: &mut S, _: usize) -> Option<N> {
        None
    }
}
