[package]
name = "libafl_fandango"
version.workspace = true
edition.workspace = true
authors.workspace = true

[features]
default = ["std"]
std = ["libafl/std", "libafl_bolts/std", "libafl_bolts/serdeany_autoreg"]

[dependencies]
fandango = { path = ".." }
fandango-runtime = { path = "../runtime" }

libafl = { workspace = true, features = ["rand_trait"] }
libafl_bolts = { workspace = true, features = ["rand_trait"] }
mappable-rc.workspace = true
serde = { workspace = true, features = ["alloc", "derive"] }

[dev-dependencies]
rand = { workspace = true, features = ["std_rng"] }
fandango-targets = { path = "../targets", features = ["xml", "serde"] }
num-rational = { workspace = true }

[lints]
workspace = true
