//! See how many generated C programs compile with gcc, using an unconstrained grammar.
//! This is similar to c_lang_validity_only.rs, but uses an unconstrained grammar.
//! Emits LaTeX macros with the results.
// Note: This file uses code generated by Copilot.

use anyhow::Error;
use fandango::tuple_list::tuple_list;
use fandango::typing::Structured;
use fandango::typing::{Node, StaticDiscriminable};
use fandango::visitor::Visitor;
use fandango::visitor::navigation::CountNodes;
use fandango::visitor::write::WriteVisitor;
use fandango_core::generation::Generated;
use fandango_core::visitor::kpath::{KPathUpdate, KPaths};
use fandango_runtime::evolvers::Evolver;
use fandango_runtime::evolvers::basic::BasicEvolver;
use fandango_runtime::evolvers::multi::{FitnessMeasurerTuple, MeasurementsCombined, Nsga2Evolver};
use fandango_runtime::measurement::{FitnessMeasurer, HasFitness};
use fandango_runtime::measurement::{HasMeasurement, HasViolations};
use fandango_runtime::operators::{DepthLimiter, NodeScan};
use fandango_runtime::population::Individual;
use fandango_targets::clang::{
    self, CombinedConstraintFitnessMeasurer, CombinedConstraintVisitor, MediantSum, TypeMut,
    nonterminal_start,
};
use num_rational::Ratio;
use rand::SeedableRng;
use rand::rngs::StdRng;
use std::cmp::Reverse;
use std::collections::VecDeque;
use std::convert::Infallible;
use std::num::NonZeroUsize;
use std::process::{Command, Stdio};

// Up to n struct definitions
struct StructGoal {
    n: usize,
}

impl<'a, N> FitnessMeasurer<'a, N> for StructGoal
where
    N: Node,
{
    type Measurement = Reverse<usize>;
    type Error = Infallible;

    fn evaluate(&mut self, node: &'a N) -> Result<Self::Measurement, Self::Error> {
        Ok(Reverse(
            NodeScan::new(clang::nonterminal_struct_def::DISCRIMINANT)
                .visit(node, 0)
                .unwrap()
                .continue_value()
                .unwrap()
                .matches()
                .len()
                .saturating_sub(self.n),
        ))
    }
}

// Up to n function definitions
struct FnGoal {
    n: usize,
}

impl<'a, N> FitnessMeasurer<'a, N> for FnGoal
where
    N: Node,
{
    type Measurement = Reverse<usize>;
    type Error = Infallible;

    fn evaluate(&mut self, node: &'a N) -> Result<Self::Measurement, Self::Error> {
        Ok(Reverse(
            NodeScan::new(clang::nonterminal_fn_def::DISCRIMINANT)
                .visit(node, 0)
                .unwrap()
                .continue_value()
                .unwrap()
                .matches()
                .len()
                .saturating_sub(self.n),
        ))
    }
}

struct StmtGoal {
    n: usize,
}

impl<'a, N> FitnessMeasurer<'a, N> for StmtGoal
where
    N: Node,
{
    type Measurement = Reverse<usize>;
    type Error = Infallible;

    fn evaluate(&mut self, node: &'a N) -> Result<Self::Measurement, Self::Error> {
        Ok(Reverse(
            self.n.saturating_sub(
                NodeScan::new(clang::nonterminal_stmt::DISCRIMINANT)
                    .visit(node, 0)
                    .unwrap()
                    .continue_value()
                    .unwrap()
                    .matches()
                    .len(),
            ),
        ))
    }
}

fn run_once_validity_and_size(
    all_population: &mut Vec<nonterminal_start>,
    fine_print: bool,
    print_successful_compile: bool,
    print_unsuccessful_compile: bool,
) -> Result<(i32, i32, i32, f32, f32), Error> {
    let structs = StructGoal { n: 1 };
    let fns = FnGoal { n: 1 };
    let stmts = StmtGoal { n: 5 };

    let mut runtime = Nsga2Evolver::new::<clang::nonterminal_start>(
        (structs, (fns, (stmts, CombinedConstraintFitnessMeasurer))),
        (),
        100,
        1000,
        Ratio::new(80, 100),
    )
    .expect("Should be valid.");

    // For returning
    let mut number_of_generated_programs = 0;
    let mut number_of_programs_with_fitness_1 = 0;
    let mut number_of_programs_accepted_by_gcc = 0;

    let generator = DepthLimiter::new(clang::STRUCTURE.inner(), 100);
    let mut generators = tuple_list!(generator);
    let mut sampler = StdRng::from_os_rng();

    let mut population = runtime.initial(&mut generators, &mut sampler)?;

    // Time the generation process
    let start_time = std::time::Instant::now();
    for i in 0..100 {
        let fitness = population
            .iter()
            .map(|i| i.measurement().fitness().1.1.1.mediant())
            .fold(0.0f64, |v, r| v + *r.numer() as f64 / *r.denom() as f64)
            / population.len() as f64;
        if fitness == 1.0 {
            println!("saturated fitness at generation {i}");
            break;
        }
        println!("average fitness at generation {i}: {fitness}");
        population = runtime.step(&mut generators, &mut sampler, population)?;
    }

    population.sort_by(|i1, i2| i1.node().cmp(i2.node()));
    population.dedup_by(|i1, i2| i1.node() == i2.node());

    let elapsed_gen = start_time.elapsed();

    if fine_print {
        println!("Population:");
    }
    // Time the gcc checking process
    let start_time_compile = std::time::Instant::now();
    for (i, candidate) in population.into_iter().enumerate() {
        if fine_print {
            println!("Candidate #{i} ===============================================");
        }
        number_of_generated_programs += 1;
        // If fitness is 1.0, it means no violations.
        // Try to pass the candidate to gcc.
        // Write the candidate to a file, pre-pended with necessary includes.
        // Then run `gcc -x c -o /dev/null - <file>`.
        // If gcc returns 0, it means the program is valid.
        // If gcc returns non-zero, it means the program is invalid.
        // First, check fitness ratio to see if it's 1.0
        let constraint_fitness = candidate.measurement().fitness().1.1.1.mediant();
        if *constraint_fitness.numer() == *constraint_fitness.denom() {
            number_of_programs_with_fitness_1 += 1;
        } else {
            if fine_print {
                println!("Candidate has fitness less than 1.0, skipping gcc check.");
                println!("Fitness: {:?}", candidate.measurement().fitness());
            }
            continue;
        }

        let process_or_not = Command::new("gcc")
            .arg("-x")
            .arg("c")
            .arg("-o")
            .arg("/dev/null")
            .arg("-")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn();

        let mut process = match process_or_not {
            Ok(p) => p,
            Err(e) => {
                if fine_print {
                    println!("Failed to spawn gcc process: {}", e);
                }
                continue;
            }
        };

        let stdin = process.stdin.as_mut().expect("Failed to open stdin");
        use std::io::Write;
        writeln!(stdin, "#include <stdio.h>").unwrap();
        // writeln!(stdin, "#include <stdlib.h>").unwrap();
        writeln!(stdin, "#include <stdbool.h>").unwrap();
        // writeln!(stdin, "#include <string.h>").unwrap();
        writeln!(stdin).unwrap();
        // Wrap this in a main function.
        // writeln!(stdin, "int main() {{").unwrap();
        stdin
            .write_all(
                &WriteVisitor::new(Vec::new())
                    .visit(candidate.node(), 0)?
                    .continue_value()
                    .unwrap()
                    .output(),
            )
            .unwrap();
        // writeln!(stdin, " return 0; }}").unwrap();
        // Also add a main function that returns 0 to make it a valid C program.
        writeln!(stdin).unwrap();
        writeln!(stdin, "int main() {{ return 0; }}").unwrap();

        let output = process
            .wait_with_output()
            .expect("Failed to read gcc output");

        if output.status.success() {
            // Currently, we will collect all generated programs that pass gcc.
            all_population.push(candidate.node().clone());

            if fine_print {
                println!("GCC accepted the program.");
            }
            if print_successful_compile {
                println!("---------------------------------------------------[Success]-");
                println!(
                    "{}",
                    String::from_utf8(
                        WriteVisitor::new(Vec::new())
                            .visit(candidate.node(), 0)?
                            .continue_value()
                            .unwrap()
                            .output()
                    )?
                );
            }
            number_of_programs_accepted_by_gcc += 1;
        } else {
            if fine_print {
                println!("GCC rejected the program.");
                println!("GCC stderr: {}", String::from_utf8_lossy(&output.stderr));
            }
            if print_unsuccessful_compile {
                println!("---------------------------------------------------[Failure]-");
                println!(
                    "{}",
                    String::from_utf8(
                        WriteVisitor::new(Vec::new())
                            .visit(candidate.node(), 0)?
                            .continue_value()
                            .unwrap()
                            .output()
                    )?
                );
            }
            if print_successful_compile {
                println!("---------------------------------------------------[Failure]-");
                println!(
                    "{}",
                    String::from_utf8(
                        WriteVisitor::new(Vec::new())
                            .visit(candidate.node(), 0)?
                            .continue_value()
                            .unwrap()
                            .output()
                    )?
                );
            }
        }
        if fine_print {
            println!("GCC exit code: {}", output.status);
            println!("GCC stdout: {}", String::from_utf8_lossy(&output.stdout));
            println!(
                "{}",
                String::from_utf8(
                    WriteVisitor::new(Vec::new())
                        .visit(candidate.node(), 0)?
                        .continue_value()
                        .unwrap()
                        .output()
                )?
            );
        }

        if fine_print {
            println!("Fitness: {:?}", candidate.measurement().fitness());
            println!("Size: {}", candidate.node().count_nodes());
        }
    }

    let elapsed_compile = start_time_compile.elapsed();

    // Print a small summary of this run
    println!("Completed a run.");

    Ok((
        number_of_generated_programs,
        number_of_programs_with_fitness_1,
        number_of_programs_accepted_by_gcc,
        elapsed_gen.as_secs_f32(),
        elapsed_compile.as_secs_f32(),
    ))
}

fn run_once_validity_and_size_single(
    all_population: &mut Vec<nonterminal_start>,
    fine_print: bool,
    print_successful_compile: bool,
    print_unsuccessful_compile: bool,
) -> Result<(i32, i32, i32, f32, f32), Error> {
    struct SingleValidityAndSizeMeasurer {
        structs: usize,
        fns: usize,
        stmts: usize,
        measurer: CombinedConstraintFitnessMeasurer,
    }

    impl<'a, N> FitnessMeasurer<'a, N> for SingleValidityAndSizeMeasurer
    where
        N: Node,
        CombinedConstraintFitnessMeasurer:
            FitnessMeasurerTuple<'a, N, Error, Measurements = CombinedConstraintVisitor>,
    {
        type Measurement = Reverse<usize>; // TODO(compat) check if FANDANGO v1.0.0 also has any guidance
        type Error = Error;

        fn evaluate(&mut self, node: &'a N) -> Result<Self::Measurement, Self::Error> {
            // fitness is strictly a function of the number of violations
            let structs = NodeScan::new(clang::nonterminal_struct_def::DISCRIMINANT)
                .visit(node, 0)
                .unwrap()
                .continue_value()
                .unwrap()
                .matches()
                .len()
                != self.structs;
            let fns = NodeScan::new(clang::nonterminal_fn_def::DISCRIMINANT)
                .visit(node, 0)
                .unwrap()
                .continue_value()
                .unwrap()
                .matches()
                .len()
                != self.fns;
            let stmts = NodeScan::new(clang::nonterminal_stmt::DISCRIMINANT)
                .visit(node, 0)
                .unwrap()
                .continue_value()
                .unwrap()
                .matches()
                .len()
                != self.stmts;
            Ok(Reverse(
                self.measurer
                    .evaluate(node)?
                    .combined()
                    .violations()
                    .violations()
                    .len()
                    + structs as usize
                    + fns as usize
                    + stmts as usize,
            ))
        }
    }

    let mut runtime = BasicEvolver::new::<nonterminal_start>(
        SingleValidityAndSizeMeasurer {
            structs: 1,
            fns: 1,
            stmts: 5,
            measurer: CombinedConstraintFitnessMeasurer,
        },
        (),
        100,
        10,
        1000,
        Ratio::new(80, 100),
    )
    .expect("Should be valid.");

    // For returning
    let mut number_of_generated_programs = 0;
    let mut number_of_programs_with_fitness_1 = 0;
    let mut number_of_programs_accepted_by_gcc = 0;

    let generator = DepthLimiter::new(clang::STRUCTURE.inner(), 100);
    let mut generators = tuple_list!(generator);
    let mut sampler = StdRng::from_os_rng();

    let mut population = runtime.initial(&mut generators, &mut sampler)?;

    // Time the generation process
    let start_time = std::time::Instant::now();
    for i in 0..100 {
        let fitness = population.iter().map(|i| i.measurement().0).sum::<usize>();
        if fitness == 0 {
            println!("saturated fitness at generation {i}");
            break;
        }
        let fitness = fitness as f64 / population.len() as f64;
        println!("average violations at generation {i}: {fitness}");
        population = runtime.step(&mut generators, &mut sampler, population)?;
    }

    population.sort_by(|i1, i2| i1.node().cmp(i2.node()));
    population.dedup_by(|i1, i2| i1.node() == i2.node());

    let elapsed_gen = start_time.elapsed();

    if fine_print {
        println!("Population:");
    }
    // Time the gcc checking process
    let start_time_compile = std::time::Instant::now();
    for (i, candidate) in population.into_iter().enumerate() {
        if fine_print {
            println!("Candidate #{i} ===============================================");
        }
        number_of_generated_programs += 1;
        // If fitness is 1.0, it means no violations.
        // Try to pass the candidate to gcc.
        // Write the candidate to a file, pre-pended with necessary includes.
        // Then run `gcc -x c -o /dev/null - <file>`.
        // If gcc returns 0, it means the program is valid.
        // If gcc returns non-zero, it means the program is invalid.
        // First, check fitness ratio to see if it's 1.0
        let constraint_fitness = candidate.measurement().0;
        if constraint_fitness == 0 {
            number_of_programs_with_fitness_1 += 1;
        } else {
            if fine_print {
                println!("Candidate has fitness less than 1.0, skipping gcc check.");
                println!("Fitness: {:?}", 1.0f64 / candidate.measurement().0 as f64);
            }
            continue;
        }

        let process_or_not = Command::new("gcc")
            .arg("-x")
            .arg("c")
            .arg("-o")
            .arg("/dev/null")
            .arg("-")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn();

        let mut process = match process_or_not {
            Ok(p) => p,
            Err(e) => {
                if fine_print {
                    println!("Failed to spawn gcc process: {}", e);
                }
                continue;
            }
        };

        let stdin = process.stdin.as_mut().expect("Failed to open stdin");
        use std::io::Write;
        writeln!(stdin, "#include <stdio.h>").unwrap();
        // writeln!(stdin, "#include <stdlib.h>").unwrap();
        writeln!(stdin, "#include <stdbool.h>").unwrap();
        // writeln!(stdin, "#include <string.h>").unwrap();
        writeln!(stdin).unwrap();
        // Wrap this in a main function.
        // writeln!(stdin, "int main() {{").unwrap();
        stdin
            .write_all(
                &WriteVisitor::new(Vec::new())
                    .visit(candidate.node(), 0)?
                    .continue_value()
                    .unwrap()
                    .output(),
            )
            .unwrap();
        // writeln!(stdin, " return 0; }}").unwrap();
        // Also add a main function that returns 0 to make it a valid C program.
        writeln!(stdin).unwrap();
        writeln!(stdin, "int main() {{ return 0; }}").unwrap();

        let output = process
            .wait_with_output()
            .expect("Failed to read gcc output");

        if output.status.success() {
            // Currently, we will collect all generated programs that pass gcc.
            all_population.push(candidate.node().clone());

            if fine_print {
                println!("GCC accepted the program.");
            }
            if print_successful_compile {
                println!("---------------------------------------------------[Success]-");
                println!(
                    "{}",
                    String::from_utf8(
                        WriteVisitor::new(Vec::new())
                            .visit(candidate.node(), 0)?
                            .continue_value()
                            .unwrap()
                            .output()
                    )?
                );
            }
            number_of_programs_accepted_by_gcc += 1;
        } else {
            if fine_print {
                println!("GCC rejected the program.");
                println!("GCC stderr: {}", String::from_utf8_lossy(&output.stderr));
            }
            if print_unsuccessful_compile {
                println!("---------------------------------------------------[Failure]-");
                println!(
                    "{}",
                    String::from_utf8(
                        WriteVisitor::new(Vec::new())
                            .visit(candidate.node(), 0)?
                            .continue_value()
                            .unwrap()
                            .output()
                    )?
                );
            }
            if print_successful_compile {
                println!("---------------------------------------------------[Failure]-");
                println!(
                    "{}",
                    String::from_utf8(
                        WriteVisitor::new(Vec::new())
                            .visit(candidate.node(), 0)?
                            .continue_value()
                            .unwrap()
                            .output()
                    )?
                );
            }
        }
        if fine_print {
            println!("GCC exit code: {}", output.status);
            println!("GCC stdout: {}", String::from_utf8_lossy(&output.stdout));
            println!(
                "{}",
                String::from_utf8(
                    WriteVisitor::new(Vec::new())
                        .visit(candidate.node(), 0)?
                        .continue_value()
                        .unwrap()
                        .output()
                )?
            );
        }

        if fine_print {
            println!("Fitness: {:?}", candidate.measurement().fitness());
            println!("Size: {}", candidate.node().count_nodes());
        }
    }

    let elapsed_compile = start_time_compile.elapsed();

    // Print a small summary of this run
    println!("Completed a run.");

    Ok((
        number_of_generated_programs,
        number_of_programs_with_fitness_1,
        number_of_programs_accepted_by_gcc,
        elapsed_gen.as_secs_f32(),
        elapsed_compile.as_secs_f32(),
    ))
}

fn run_once_validity_only(
    all_population: &mut Vec<nonterminal_start>,
    fine_print: bool,
    print_successful_compile: bool,
) -> Result<(i32, i32, i32, f32, f32), Error> {
    let mut runtime = Nsga2Evolver::new::<nonterminal_start>(
        CombinedConstraintFitnessMeasurer,
        (),
        100,
        1000,
        Ratio::new(80, 100),
    )
    .expect("Should be valid.");

    // For returning
    let mut number_of_generated_programs = 0;
    let mut number_of_programs_with_fitness_1 = 0;
    let mut number_of_programs_accepted_by_gcc = 0;

    let generator = DepthLimiter::new(clang::STRUCTURE.inner(), 100);
    let mut generators = tuple_list!(generator);
    let mut sampler = StdRng::from_os_rng();

    let mut population = runtime.initial(&mut generators, &mut sampler)?;

    // Time the generation process
    let start_time = std::time::Instant::now();
    for i in 0..100 {
        let fitness = population
            .iter()
            .map(|i| i.measurement().fitness().mediant())
            .fold(0.0f64, |v, r| v + *r.numer() as f64 / *r.denom() as f64)
            / population.len() as f64;
        if fitness == 1.0 {
            println!("saturated fitness at generation {i}");
            break;
        }
        println!("average fitness at generation {i}: {fitness}");
        population = runtime.step(&mut generators, &mut sampler, population)?;
    }

    population.sort_by(|i1, i2| i1.node().cmp(i2.node()));
    population.dedup_by(|i1, i2| i1.node() == i2.node());

    let elapsed_gen = start_time.elapsed();

    if fine_print {
        println!("Population:");
    }
    // Time the gcc checking process
    let start_time_compile = std::time::Instant::now();
    for (i, candidate) in population.into_iter().enumerate() {
        if fine_print {
            println!("Candidate #{i} ===============================================");
        }
        number_of_generated_programs += 1;
        // If fitness is 1.0, it means no violations.
        // Try to pass the candidate to gcc.
        // Write the candidate to a file, pre-pended with necessary includes.
        // Then run `gcc -x c -o /dev/null - <file>`.
        // If gcc returns 0, it means the program is valid.
        // If gcc returns non-zero, it means the program is invalid.
        // First, check fitness ratio to see if it's 1.0
        let fitness = candidate.measurement().fitness().mediant();
        if *fitness.numer() == *fitness.denom() {
            number_of_programs_with_fitness_1 += 1;
        } else {
            if fine_print {
                println!("Candidate has fitness less than 1.0, skipping gcc check.");
                println!("Fitness: {:?}", candidate.measurement().fitness());
            }
            continue;
        }

        let process_or_not = Command::new("gcc")
            .arg("-x")
            .arg("c")
            .arg("-o")
            .arg("/dev/null")
            .arg("-")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn();

        let mut process = match process_or_not {
            Ok(p) => p,
            Err(e) => {
                if fine_print {
                    println!("Failed to spawn gcc process: {}", e);
                }
                continue;
            }
        };

        let stdin = process.stdin.as_mut().expect("Failed to open stdin");
        use std::io::Write;
        writeln!(stdin, "#include <stdio.h>").unwrap();
        writeln!(stdin, "#include <stdbool.h>").unwrap();
        writeln!(stdin).unwrap();
        // Wrap this in a main function.
        stdin
            .write_all(
                &WriteVisitor::new(Vec::new())
                    .visit(candidate.node(), 0)?
                    .continue_value()
                    .unwrap()
                    .output(),
            )
            .unwrap();
        // Also add a main function that returns 0 to make it a valid C program.
        writeln!(stdin).unwrap();
        writeln!(stdin, "int main() {{ return 0; }}").unwrap();

        let output = process
            .wait_with_output()
            .expect("Failed to read gcc output");

        if output.status.success() {
            // Currently, we will collect all generated programs that pass gcc.
            all_population.push(candidate.node().clone());

            if fine_print {
                println!("GCC accepted the program.");
            }
            if print_successful_compile {
                println!(
                    "{}",
                    String::from_utf8(
                        WriteVisitor::new(Vec::new())
                            .visit(candidate.node(), 0)?
                            .continue_value()
                            .unwrap()
                            .output()
                    )?
                );
            }
            number_of_programs_accepted_by_gcc += 1;
        } else if fine_print {
            println!("GCC rejected the program.");
            println!("GCC stderr: {}", String::from_utf8_lossy(&output.stderr));
        }
        if fine_print {
            println!("GCC exit code: {}", output.status);
            println!("GCC stdout: {}", String::from_utf8_lossy(&output.stdout));
            println!(
                "{}",
                String::from_utf8(
                    WriteVisitor::new(Vec::new())
                        .visit(candidate.node(), 0)?
                        .continue_value()
                        .unwrap()
                        .output()
                )?
            );
        }

        if fine_print {
            println!("Fitness: {:?}", candidate.measurement().fitness());
            println!("Size: {}", candidate.node().count_nodes());
        }
    }

    let elapsed_compile = start_time_compile.elapsed();

    // Print a small summary of this run
    println!("Completed a run.");

    Ok((
        number_of_generated_programs,
        number_of_programs_with_fitness_1,
        number_of_programs_accepted_by_gcc,
        elapsed_gen.as_secs_f32(),
        elapsed_compile.as_secs_f32(),
    ))
}

fn run_once_validity_only_single(
    all_population: &mut Vec<nonterminal_start>,
    fine_print: bool,
    print_successful_compile: bool,
) -> Result<(i32, i32, i32, f32, f32), Error> {
    struct SingleValidityMeasurer {
        measurer: CombinedConstraintFitnessMeasurer,
    }

    impl<'a, N> FitnessMeasurer<'a, N> for SingleValidityMeasurer
    where
        N: Node,
        CombinedConstraintFitnessMeasurer:
            FitnessMeasurerTuple<'a, N, Error, Measurements = CombinedConstraintVisitor>,
    {
        type Measurement = Reverse<usize>; // TODO(compat) check if FANDANGO v1.0.0 also has any guidance
        type Error = Error;

        fn evaluate(&mut self, node: &'a N) -> Result<Self::Measurement, Self::Error> {
            // fitness is strictly a function of the number of violations
            Ok(Reverse(
                self.measurer
                    .evaluate(node)?
                    .combined()
                    .violations()
                    .violations()
                    .len(),
            ))
        }
    }

    let mut runtime = BasicEvolver::new::<nonterminal_start>(
        SingleValidityMeasurer {
            measurer: CombinedConstraintFitnessMeasurer,
        },
        (),
        100,
        10,
        1000,
        Ratio::new(80, 100),
    )
    .expect("Should be valid.");

    // For returning
    let mut number_of_generated_programs = 0;
    let mut number_of_programs_with_fitness_1 = 0;
    let mut number_of_programs_accepted_by_gcc = 0;

    let generator = DepthLimiter::new(clang::STRUCTURE.inner(), 100);
    let mut generators = tuple_list!(generator);
    let mut sampler = StdRng::from_os_rng();

    let mut population = runtime.initial(&mut generators, &mut sampler)?;

    // Time the generation process
    let start_time = std::time::Instant::now();
    for i in 0..100 {
        let fitness = population.iter().map(|i| i.measurement().0).sum::<usize>();
        if fitness == 0 {
            println!("saturated fitness at generation {i}");
            break;
        }
        let fitness = fitness as f64 / population.len() as f64;
        println!("average violations at generation {i}: {fitness}");
        population = runtime.step(&mut generators, &mut sampler, population)?;
    }

    population.sort_by(|i1, i2| i1.node().cmp(i2.node()));
    population.dedup_by(|i1, i2| i1.node() == i2.node());

    let elapsed_gen = start_time.elapsed();

    if fine_print {
        println!("Population:");
    }
    // Time the gcc checking process
    let start_time_compile = std::time::Instant::now();
    for (i, candidate) in population.into_iter().enumerate() {
        if fine_print {
            println!("Candidate #{i} ===============================================");
        }
        number_of_generated_programs += 1;
        // If fitness is 1.0, it means no violations.
        // Try to pass the candidate to gcc.
        // Write the candidate to a file, pre-pended with necessary includes.
        // Then run `gcc -x c -o /dev/null - <file>`.
        // If gcc returns 0, it means the program is valid.
        // If gcc returns non-zero, it means the program is invalid.
        // First, check fitness ratio to see if it's 1.0
        let constraint_fitness = candidate.measurement().0;
        if constraint_fitness == 0 {
            number_of_programs_with_fitness_1 += 1;
        } else {
            if fine_print {
                println!("Candidate has fitness less than 1.0, skipping gcc check.");
                println!("Fitness: {:?}", 1.0f64 / candidate.measurement().0 as f64);
            }
            continue;
        }

        let process_or_not = Command::new("gcc")
            .arg("-x")
            .arg("c")
            .arg("-o")
            .arg("/dev/null")
            .arg("-")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn();

        let mut process = match process_or_not {
            Ok(p) => p,
            Err(e) => {
                if fine_print {
                    println!("Failed to spawn gcc process: {}", e);
                }
                continue;
            }
        };

        let stdin = process.stdin.as_mut().expect("Failed to open stdin");
        use std::io::Write;
        writeln!(stdin, "#include <stdio.h>").unwrap();
        writeln!(stdin, "#include <stdbool.h>").unwrap();
        writeln!(stdin).unwrap();
        // Wrap this in a main function.
        stdin
            .write_all(
                &WriteVisitor::new(Vec::new())
                    .visit(candidate.node(), 0)?
                    .continue_value()
                    .unwrap()
                    .output(),
            )
            .unwrap();
        // Also add a main function that returns 0 to make it a valid C program.
        writeln!(stdin).unwrap();
        writeln!(stdin, "int main() {{ return 0; }}").unwrap();

        let output = process
            .wait_with_output()
            .expect("Failed to read gcc output");

        if output.status.success() {
            // Currently, we will collect all generated programs that pass gcc.
            all_population.push(candidate.node().clone());

            if fine_print {
                println!("GCC accepted the program.");
            }
            if print_successful_compile {
                println!(
                    "{}",
                    String::from_utf8(
                        WriteVisitor::new(Vec::new())
                            .visit(candidate.node(), 0)?
                            .continue_value()
                            .unwrap()
                            .output()
                    )?
                );
            }
            number_of_programs_accepted_by_gcc += 1;
        } else if fine_print {
            println!("GCC rejected the program.");
            println!("GCC stderr: {}", String::from_utf8_lossy(&output.stderr));
        }
        if fine_print {
            println!("GCC exit code: {}", output.status);
            println!("GCC stdout: {}", String::from_utf8_lossy(&output.stdout));
            println!(
                "{}",
                String::from_utf8(
                    WriteVisitor::new(Vec::new())
                        .visit(candidate.node(), 0)?
                        .continue_value()
                        .unwrap()
                        .output()
                )?
            );
        }

        if fine_print {
            println!("Fitness: {:?}", candidate.measurement().fitness());
            println!("Size: {}", candidate.node().count_nodes());
        }
    }

    let elapsed_compile = start_time_compile.elapsed();

    // Print a small summary of this run
    println!("Completed a run.");

    Ok((
        number_of_generated_programs,
        number_of_programs_with_fitness_1,
        number_of_programs_accepted_by_gcc,
        elapsed_gen.as_secs_f32(),
        elapsed_compile.as_secs_f32(),
    ))
}

fn run_once_unconstrained(
    all_that_compile: &mut Vec<nonterminal_start>,
    fine_print: bool,
    print_successful_compile: bool,
) -> Result<(i32, i32, i32, f32, f32), Error> {
    // For returning
    let mut number_of_generated_programs = 0;
    let number_of_programs_with_fitness_1 = 0;
    let mut number_of_programs_accepted_by_gcc = 0;

    let generator = DepthLimiter::new(clang::STRUCTURE.inner(), 100);
    let mut generators = tuple_list!(generator);
    let mut sampler = StdRng::from_os_rng();

    let mut population = VecDeque::new();

    // Time the generation process
    let start_time = std::time::Instant::now();
    for _i in 0..100 {
        let the_input = clang::nonterminal_start::generate(&mut sampler, &mut generators, 0);
        population.push_back(the_input.clone());
    }

    let elapsed_gen = start_time.elapsed();

    if fine_print {
        println!("Population:");
    }
    // Time the gcc checking process
    let start_time_compile = std::time::Instant::now();
    for (i, candidate) in population.into_iter().enumerate() {
        if fine_print {
            println!("Candidate #{i} ===============================================");
        }
        number_of_generated_programs += 1;
        // If fitness is 1.0, it means no violations.
        // Try to pass the candidate to gcc.
        // Write the candidate to a file, pre-pended with necessary includes.
        // Then run `gcc -x c -o /dev/null - <file>`.
        // If gcc returns 0, it means the program is valid.
        // If gcc returns non-zero, it means the program is invalid.
        // First, check fitness ratio to see if it's 1.0
        let process_or_not = Command::new("gcc")
            .arg("-x")
            .arg("c")
            .arg("-o")
            .arg("/dev/null")
            .arg("-")
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn();

        let mut process = match process_or_not {
            Ok(p) => p,
            Err(e) => {
                if fine_print {
                    println!("Failed to spawn gcc process: {}", e);
                }
                continue;
            }
        };

        let stdin = process.stdin.as_mut().expect("Failed to open stdin");
        use std::io::Write;
        writeln!(stdin, "#include <stdio.h>").unwrap();
        // writeln!(stdin, "#include <stdlib.h>").unwrap();
        writeln!(stdin, "#include <stdbool.h>").unwrap();
        // writeln!(stdin, "#include <string.h>").unwrap();
        writeln!(stdin).unwrap();
        // Wrap this in a main function.
        stdin
            .write_all(
                &WriteVisitor::new(Vec::new())
                    .visit(&candidate, 0)?
                    .continue_value()
                    .unwrap()
                    .output(),
            )
            .unwrap();
        // Also add a main function that returns 0 to make it a valid C program.
        writeln!(stdin).unwrap();
        writeln!(stdin, "int main() {{ return 0; }}").unwrap();

        let output = process
            .wait_with_output()
            .expect("Failed to read gcc output");

        if output.status.success() {
            all_that_compile.push(candidate.clone());
            if fine_print {
                println!("GCC accepted the program.");
            }
            if print_successful_compile {
                println!(
                    "{}",
                    String::from_utf8(
                        WriteVisitor::new(Vec::new())
                            .visit(&candidate, 0)?
                            .continue_value()
                            .unwrap()
                            .output()
                    )?
                );
            }
            number_of_programs_accepted_by_gcc += 1;
        } else if fine_print {
            println!("GCC rejected the program.");
            println!("GCC stderr: {}", String::from_utf8_lossy(&output.stderr));
        }
        if fine_print {
            println!("GCC exit code: {}", output.status);
            println!("GCC stdout: {}", String::from_utf8_lossy(&output.stdout));
            println!(
                "{}",
                String::from_utf8(
                    WriteVisitor::new(Vec::new())
                        .visit(&candidate, 0)?
                        .continue_value()
                        .unwrap()
                        .output()
                )?
            );
        }
    }

    let elapsed_compile = start_time_compile.elapsed();

    // Print a small summary of this run
    println!("Completed a run.");

    Ok((
        number_of_generated_programs,
        number_of_programs_with_fitness_1,
        number_of_programs_accepted_by_gcc,
        elapsed_gen.as_secs_f32(),
        elapsed_compile.as_secs_f32(),
    ))
}

#[derive(Copy, Clone)]
enum ReplMode {
    Multi,
    Single,
}

#[derive(Copy, Clone)]
enum ReplConstraints {
    Unconstrained,
    ValidityOnly,
    ValidityAndSize,
}

#[allow(deprecated)]
fn main_repl(
    mode: ReplMode,
    constraints: ReplConstraints,
) -> Result<(f32, i32, i32, i32, f32, f32), Error> {
    // Run for 1 minute

    // Get ready for statistics for whole run
    let mut total_programs_generated = 0;
    let mut total_programs_with_fitness_1 = 0;
    let mut total_programs_accepted_by_gcc = 0;
    let mut total_elapsed_gen = 0.0;
    let mut total_elapsed_compile = 0.0;

    // Initialize KPath stuff for the C language grammar.
    let mut kpaths = KPaths::new::<TypeMut<'static>>(
        NonZeroUsize::new(5).unwrap(),
        clang::nonterminal_start::ROOT.inner(),
    );

    let mut updater: KPathUpdate<'_, true> = KPathUpdate::inserting(&mut kpaths);

    // Also part of initialization:
    let (mut _zero, _total) = updater.kpaths().k_paths();

    // Collect all generated programs by passing this into the run_once calls
    let mut all_that_compile: Vec<nonterminal_start> = Vec::new();

    // let start = std::time::Instant::now();
    // Actually, just run for 1 minute for testing
    // let duration = std::time::Duration::from_secs(60);
    let target_time_seconds = 60;
    let mut total_elapsed_gen_and_compile = 0.0;
    loop {
        let (generated, fitness_1, accepted, elapsed_gen, elapsed_compile) =
            match (mode, constraints) {
                (_, ReplConstraints::Unconstrained) => {
                    run_once_unconstrained(&mut all_that_compile, false, false)
                }
                (ReplMode::Multi, ReplConstraints::ValidityOnly) => {
                    run_once_validity_only(&mut all_that_compile, false, false)
                }
                (ReplMode::Single, ReplConstraints::ValidityOnly) => {
                    run_once_validity_only_single(&mut all_that_compile, false, false)
                }
                (ReplMode::Multi, ReplConstraints::ValidityAndSize) => {
                    run_once_validity_and_size(&mut all_that_compile, false, false, false)
                }
                (ReplMode::Single, ReplConstraints::ValidityAndSize) => {
                    run_once_validity_and_size_single(&mut all_that_compile, false, false, false)
                }
            }?;
        total_programs_generated += generated;
        total_programs_with_fitness_1 += fitness_1;
        total_programs_accepted_by_gcc += accepted;
        total_elapsed_gen += elapsed_gen;
        total_elapsed_compile += elapsed_compile;
        total_elapsed_gen_and_compile += elapsed_gen + elapsed_compile;
        println!("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~");
        if total_elapsed_gen_and_compile >= target_time_seconds as f32 {
            break;
        }
    }

    // Once all is said and done, compute KPaths
    for gprog in all_that_compile {
        updater = updater.visit(&gprog, 0).unwrap().continue_value().unwrap();
    }

    // Produce KPath results
    let (uncovered, total) = updater.kpaths().k_paths();

    println!("Covered: {} of: {}", total - uncovered, total);

    // print a macro with the covered %
    let covered_percentage = if total == 0 {
        0.0
    } else {
        (total - uncovered) as f32 / total as f32 * 100.0
    };

    // Return results
    Ok((
        covered_percentage,
        total_programs_generated,
        total_programs_with_fitness_1,
        total_programs_accepted_by_gcc,
        total_elapsed_gen,
        total_elapsed_compile,
    ))
}

#[allow(deprecated)]
fn main() -> Result<(), Error> {
    let [mode, constraints] = std::env::args()
        .skip(1)
        .collect::<Vec<_>>()
        .try_into()
        .map_err(|_| {
            anyhow::Error::msg("Invalid argument; expected a mode and a set of constraints")
        })?;
    let mode = match mode.as_str() {
        "multi" => ReplMode::Multi,
        "single" => ReplMode::Single,
        _ => {
            return Err(anyhow::Error::msg(
                "Invalid mode; expected either `multi' or `single'",
            ));
        }
    };
    let constraints = match constraints.as_str() {
        "unconstrained" => ReplConstraints::Unconstrained,
        "validity" => ReplConstraints::ValidityOnly,
        "both" => ReplConstraints::ValidityAndSize,
        _ => {
            return Err(anyhow::Error::msg(
                "Invalid constraints; expected `unconstrained', `validity', or `both'",
            ));
        }
    };
    let name = match (mode, constraints) {
        (_, ReplConstraints::Unconstrained) => "unconstrained",
        (ReplMode::Multi, ReplConstraints::ValidityOnly) => "multiValid",
        (ReplMode::Single, ReplConstraints::ValidityOnly) => "singleValid",
        (ReplMode::Multi, ReplConstraints::ValidityAndSize) => "multiValidAndSized",
        (ReplMode::Single, ReplConstraints::ValidityAndSize) => "singleValidAndSized",
    };

    let mut total_covered_percentage = 0.0;
    let mut total_programs_generated = 0;
    let mut total_programs_with_fitness_1 = 0;
    let mut total_programs_accepted_by_gcc = 0;
    let mut total_elapsed_gen = 0.0;
    let mut total_elapsed_compile = 0.0;

    let num_runs = 5;

    for run in 1..=num_runs {
        println!("Starting run {}/{}...", run, num_runs);
        let (
            run_covered_percentage,
            run_programs_generated,
            run_programs_with_fitness_1,
            run_programs_accepted_by_gcc,
            run_elapsed_gen,
            run_elapsed_compile,
        ) = main_repl(mode, constraints)?;
        total_covered_percentage += run_covered_percentage;
        total_programs_generated += run_programs_generated;
        total_programs_with_fitness_1 += run_programs_with_fitness_1;
        total_programs_accepted_by_gcc += run_programs_accepted_by_gcc;
        total_elapsed_gen += run_elapsed_gen;
        total_elapsed_compile += run_elapsed_compile;
        println!("Finished run {}/{}.", run, num_runs);
    }

    // Summarize runs
    let average_covered_percentage = if num_runs == 0 {
        0.0
    } else {
        total_covered_percentage / num_runs as f32
    };

    let average_programs_generated = if num_runs == 0 {
        0
    } else {
        total_programs_generated / num_runs
    };

    let average_programs_with_fitness_1 = if num_runs == 0 {
        0
    } else {
        total_programs_with_fitness_1 / num_runs
    };

    let average_programs_accepted_by_gcc = if num_runs == 0 {
        0
    } else {
        total_programs_accepted_by_gcc / num_runs
    };

    let average_elapsed_gen = if num_runs == 0 {
        0.0
    } else {
        total_elapsed_gen / num_runs as f32
    };

    let average_elapsed_compile = if num_runs == 0 {
        0.0
    } else {
        total_elapsed_compile / num_runs as f32
    };

    println!("Averages over {} runs:", num_runs);

    println!(
        "\\newcommand{{\\{name}KPathCoverageAvgRs}}{{{:.2}\\%\\xspace}}",
        average_covered_percentage
    );

    println!(
        "\\newcommand{{\\{name}TotalAvgRs}}{{{:.2}\\xspace}}",
        average_programs_generated
    );

    println!(
        "\\newcommand{{\\{name}FitOneAvgRs}}{{{:.2}\\xspace}}",
        average_programs_with_fitness_1
    );

    println!(
        "\\newcommand{{\\{name}CompileAvgRs}}{{{:.2}\\xspace}}",
        average_programs_accepted_by_gcc
    );

    println!(
        "\\newcommand{{\\{name}GenTimeAvgRs}}{{{:.2}s\\xspace}}",
        average_elapsed_gen
    );

    println!(
        "\\newcommand{{\\{name}CompileTimeAvgRs}}{{{:.2}s\\xspace}}",
        average_elapsed_compile
    );

    println!(
        "\\newcommand{{\\{name}TotalTimeAvgRs}}{{{:.2}s\\xspace}}",
        average_elapsed_gen + average_elapsed_compile
    );

    // Also write these macros to a .txt file
    let mut file = std::fs::File::create("c_lang.txt")?;
    use std::io::Write;
    writeln!(
        file,
        "\\newcommand{{\\{name}KPathCoverageAvgRs}}{{{:.2}\\%\\xspace}}",
        average_covered_percentage
    )?;
    writeln!(
        file,
        "\\newcommand{{\\{name}TotalAvgRs}}{{{:.2}\\xspace}}",
        average_programs_generated
    )?;
    writeln!(
        file,
        "\\newcommand{{\\{name}FitOneAvgRs}}{{{:.2}\\xspace}}",
        average_programs_with_fitness_1
    )?;
    writeln!(
        file,
        "\\newcommand{{\\{name}CompileAvgRs}}{{{:.2}\\xspace}}",
        average_programs_accepted_by_gcc
    )?;
    writeln!(
        file,
        "\\newcommand{{\\{name}GenTimeAvgRs}}{{{:.2}s\\xspace}}",
        average_elapsed_gen
    )?;
    writeln!(
        file,
        "\\newcommand{{\\{name}CompileTimeAvgRs}}{{{:.2}s\\xspace}}",
        average_elapsed_compile
    )?;
    writeln!(
        file,
        "\\newcommand{{\\{name}TotalTimeAvgRs}}{{{:.2}s\\xspace}}",
        average_elapsed_gen + average_elapsed_compile
    )?;

    Ok(())
}
