[package]
name = "analysis"
version = "0.1.0"
edition = "2024"

[dependencies]
baselines = { path = ".." }

hashbrown = { workspace = true, features = ["serde"] }
linfa.workspace = true
linfa-linear.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true

[lints]
workspace = true
