[package]
name = "baselines"
version = "0.0.0"
edition = "2024"
publish = false

[features]
default = ["static_defs"]
static_defs = [
    "common/static_defs",
    "csv/static_defs",
    "rest/static_defs",
    "scriptsizec/static_defs",
    "xml/static_defs",
    "fandango-targets/static_defs"
]

[dependencies]
fandango = { path = ".." }
fandango-runtime = { path = "../runtime" }
fandango-targets = { path = "../targets" }

common = { path = "common" }

criterion.workspace = true
hashbrown.workspace = true
rand.workspace = true

[dev-dependencies]
csv = { path = "csv" }
rest = { path = "rest" }
scriptsizec = { path = "scriptsizec" }
xml = { path = "xml" }

[[bench]]
name = "baselines"
path = "benches/baselines.rs"
harness = false

[lints]
workspace = true
