[package]
name = "baselines"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
fandango = { path = ".." }
fandango-runtime = { path = "../runtime" }

common = { path = "common" }

criterion.workspace = true
hashbrown.workspace = true
rand.workspace = true

[dev-dependencies]
csv = { path = "csv", features = ["static_defs"] }
rest = { path = "rest", features = ["static_defs"] }
scriptsizec = { path = "scriptsizec", features = ["static_defs"] }
xml = { path = "xml", features = ["static_defs"] }

[[bench]]
name = "baselines"
path = "benches/baselines.rs"
harness = false

[lints]
workspace = true
