name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y libfontconfig-dev pkg-config
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: Build
        run: cargo build --verbose --workspace
      - name: Run tests
        run: cargo test --verbose --workspace
      - name: Build baselines
        run: cd baselines && cargo build --verbose --benches

  fmt:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add rustfmt
      - name: Format
        run: cargo fmt --check
      - name: Format baselines
        run: pushd baselines && cargo fmt --check && popd
      - name: Format lm3s6965
        run: pushd lm3s6965-demo && cargo fmt --check && popd

  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y libfontconfig-dev pkg-config
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add clippy
      - name: Clippy
        run: cargo clippy --all-features --workspace --tests --benches -- -D warnings
      - name: Clippy baselines
        run: pushd baselines && cargo clippy --all-features --workspace --tests --benches -- -D warnings && popd

  lm3s6965:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v4
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup target add thumbv7m-none-eabi
      - run: rustup component add clippy
      - name: Build
        run: cd lm3s6965-demo && cargo build && cargo clippy --all-features --workspace -- -D warnings