[package]
name = "fandango-targets"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[features]
default = ["static_defs"]

csv = []
rest = []
scriptsizec = []
xml = []

static_defs = []

[dev-dependencies]
rand = { workspace = true, features = ["default"] }

[dependencies]
fandango = { path = ".." }
fandango-runtime = { path = "../runtime" }

embedded-io.workspace = true
hashbrown.workspace = true

[lints]
workspace = true
