[package]
name = "fandango-targets"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[features]
default = ["static_defs"]

csv = []
rest = []
scriptsizec = []
xml = []
lualang = []
clang = []

static_defs = []

[dev-dependencies]
num-rational.workspace = true
rand = { workspace = true, features = ["default"] }

[dependencies]
rand = { workspace = true, features = ["default"] }
fandango = { path = ".." }
fandango-runtime = { path = "../runtime" }

anyhow.workspace = true
embedded-io.workspace = true
hashbrown.workspace = true
num-rational.workspace = true

[lints]
workspace = true

[[example]]
name = "xml_basic"
path = "examples/xml_basic.rs"
required-features = ["xml", "static_defs"]

[[example]]
name = "xml_multiobjective"
path = "examples/xml_multiobjective.rs"
required-features = ["xml", "static_defs"]

[[example]]
name = "c_lang_basic"
path = "examples/c_lang_basic.rs"
required-features = ["clang", "static_defs"]
